### ISSUE TITLE
Able to make iroute files for users on the server?

### ISSUE THREAD

**Issue by axlroden** [pritunl/pritunl#100]
I don't see an option to do seperate iroute's for each user, we use this extensively so would be really appreciated.

**Comment by zachhuff386** [comment]
This can be done with linked servers allowing clients to access networks on different servers. https://medium.com/pritunl-tutorials/pritunl-advanced-tutorial-2be5cc57dff8

**Comment by axlroden** [comment]
That's not what I'm asking, we have different subnets on clients that needs to be routed only there.

More information here: http://backreference.org/2009/11/15/openvpn-and-iroute/

**Comment by zachhuff386** [comment]
What's shown in that diagram can be done with linked servers. Each network would have a Pritunl node and when a client connects they will have access to all three networks. There isn't any plans to add additional client specific routing settings.
