### ISSUE TITLE
Make it easy for Chomebooks

### ISSUE THREAD

**Issue by lucasjans** [pritunl/pritunl#102]
I have a large team with a small number - maybe 10 - on Chromebooks. Setting up an OpenVPN for Chromebooks requires a strange format  - onc. The challenge is there's no one click download for the files needed to setup a VPN on a Chromebook. Converting to this file format is difficult and it would be great if Pritunl could generate it.

http://blog.dwolla.com/openvpn-on-chromeos-a-step-by-step-guide/

It certainly would tip me into buying the Pro version.

**Comment by brentley** [comment]
I want to throw on a big +1 here. 

We are a premium subscriber, and I'm happy to test any early branches/builds to validate onc generation.

**Comment by zachhuff386** [comment]
I've looked into adding this, on Chromium OS the import buttons in the certificate manager are disabled, removing the disabled attribute and importing a file crashes the browser. Importing an onc file requires going to the net-internals. It doesn't appear Google wants end-users using the onc import. Also the onc spec doesn't appear to support multiple vpn servers used for redundant configurations in Pritunl enterprise. I'm going to wait for better support by Google before adding the format.

**Comment by MACscr** [comment]
How is it that commercial vpn providers that use openvpn are able to create simple configuration options for chromebooks to work with their system, but not normal self hosted users like us? I dont know enough about VPN's to help at all and I definitely share your frustration with getting openvpn to work on a chromebook. Is the complication some of the routing that is done client side that these commercial providers dont need? I mean the process that this company seems to use https://www.safervpn.com/guides?platform=chromebook&protocol=openvpn is pretty straightforward.
