### ISSUE TITLE
virtual IP address - Static Leases

### ISSUE THREAD

**Issue by MichaelAndoid** [pritunl/pritunl#103]
How can i force one user have always the same virtual IP address?

There is no option wen i create a user to force have always the same virtual IP address?

Best Regards

**Comment by zachhuff386** [comment]
All virtual IP addresses are static, if multiple connections is enabled additional connections from a user will use a dynamic IP address.

**Comment by MichaelAndoid** [comment]
They are static?

Today i make a reboot to a client pritunl and the internal IP changed.
Before reboot 192.168.218.3, after reboot  192.168.218.254.
