### ISSUE TITLE
 Uptime Bug?

### ISSUE THREAD

**Issue by MichaelAndoid** [pritunl/pritunl#105]
In the front end /#/servers the uptime afer 24 hours reset to 0d 0h 1 m 1s.
But none of connections is droped and server Output its ok without messages, when this happens.

This is a bug?

**Comment by zachhuff386** [comment]
I wasn't able to reproduce this, possibly an issue with the browser. IE has alot of issues and isn't supported or tested.

**Comment by endrju81** [comment]
Same problem. Newest version of pritunl on ubuntu 14.04.2
