### ISSUE TITLE
Hard stop & restart

### ISSUE THREAD

**Issue by colb** [pritunl/pritunl#107]
Hi,

Printunl seems to stop and restart randomly, sometimes several times per hour, regardless that i'm connected or not via openvpn

[guarded-fields-8283] Sun May 17 08:40:51 2015 event_wait : Interrupted system call (code=4)
[guarded-fields-8283] Sun May 17 08:40:51 2015 SIGINT[hard,] received, process exiting

Pritunl is installed on a OpenVZ VPS + Ubuntu 14.04
Nothing in the log file.

**Comment by zachhuff386** [comment]
Get the output of `ifconfig -a`,  `route -n` and the port, protocol, network, bind address of server.
