### ISSUE TITLE
CentOS 7 Kernel Hung

### ISSUE THREAD

**Issue by dcplaya** [pritunl/pritunl#109]
On a fresh install of Pritunl in CentOS 7, after running for about a day, I get the following error in the terminal.

![2015-05-26 09_07_54-vm 108 vpn](https://cloud.githubusercontent.com/assets/1105320/7813211/f78ee546-0386-11e5-9cc7-68b14c9fb694.jpg)

I have to reboot to bring all access back to the VM.

**Comment by zachhuff386** [comment]
This is an issue with the system most likely overloaded disk
