### ISSUE TITLE
No bytes_received or bytes_sent when querying API

### ISSUE THREAD

**Issue by jeantoulza** [pritunl/pritunl#110]
Hello,
I was looking for a way to get some user statistics like OpenVPN do with its status file and found in the pritunl API that I can query these data using GET /user/:organization_id.
However, it does not return any bytes_received nor bytes_sent field like it should be according to the documentation. Here is my output:
```
    {
        "disabled": false,
        "email": null,
        "id": "5564cc3cb0de0c096f8b254a",
        "name": "jean_phone",
        "organization": "5564cc10b0de0c096f8b24e8",
        "organization_name": "ORG_LAN1",
        "otp_auth": false,
        "otp_secret": "_masked_",
        "servers": [
            {
                "client_id": "0",
                "connected_since": 1432707192,
                "device_name": null,
                "id": null,
                "name": "LAN1",
                "platform": "android",
                "real_address": "_masked_",
                "status": true,
                "type": "client",
                "virt_address": "192.168.60.10"
            }
        ],
        "status": true,
        "type": "client"
    },
```
Is there something I am missing?
Thanks in advance

**Comment by zachhuff386** [comment]
Per client bandwidth was removed in version 1.0, the api documentation hasn't been updated.

**Comment by jeantoulza** [comment]
Thanks for your reply.
Could this feature be re-enabled? Why has it been removed?

**Comment by zachhuff386** [comment]
It was replaced with the server level bandwidth history, there isn't any options to enable it.
