### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by makerling** [pritunl/pritunl#111]
I was trying to work with the API in python but noticed when I updated pritunl on my ubuntu 14.04 instance today that the json output now is a bit strange:

For example when I try the GET /organization call as demonstrated on the API site I get this:

[{u'user_count': 20, u'id': u'c306a38f102c0eb54611aaa3dbacd726', u'name': u'NYC'}]

Strange 'u' prefixes. This occurs on both instances that I have it running on. Any idea how to fix this?

**Comment by zachhuff386** [comment]
The u prefix indicates the string is unicode in python.
