### ISSUE TITLE
Openvpn learn-address implementation

### ISSUE THREAD

**Issue by jeantoulza** [pritunl/pritunl#115]
Hello,
Are there plans to implement openvpn learn-address option into pritunl?
I'd like to be able to connect to clients using their computer names (or at least a memorable name) like that : https://openvpn.net/archive/openvpn-users/2006-10/msg00119.html
I'm aware that once clients have connected to pritunl, they are given a random memorable name but I can't find a way to connect to them using it. Haven't found anything in the wiki describing what's the purpose of this name.

**Comment by zachhuff386** [comment]
The name is set in the configuration file using setenv it will stay the same each time a connection is made with that configuration file. There are plans to create a custom dns server that will communicate with the database to lookup client IP addresses but very little work has been done on it.

It wouldn't be too difficult to create a script that polls the MongoDB database at an interval and lookups the user names and associated ip addresses then adds them to a dns server configuration. If you're looking to do this the `server_ip_pool` documents will have a `user_id` that can be used to lookup the user in the `users` collection to get the name.
