### ISSUE TITLE
CentOS 6 support 

### ISSUE THREAD

**Issue by centric-jim** [pritunl/pritunl#118]
Hello Zack,

This is more of a question than an issue as I'm not sure what would be the proper form for communication with you.  We're looking to evaluate Pritunl and would prefer to run it on CentOS 6(.6).  Are there any issues with doing this that you're aware of and is there a better way to communicate with you?

Thanks,
Jim

**Comment by zachhuff386** [comment]
Pritunl won't run on CentOS 6 there are packages for CentOS 7 and Amazon Linux

**Comment by centric-jim** [comment]
Is it a 'kernel' thing? Package version/dependency thing?

**Comment by zachhuff386** [comment]
Python 2.7 is required which isn't on CentOS 6 there may also be other issues with older packages.
