### ISSUE TITLE
Failed to start the server

### ISSUE THREAD

**Issue by ossvirt** [pritunl/pritunl#121]
Hello. First install of Pritunl, not sure what I'm missing. I cannot start the server. Error message -:

```
Failed to start the server, server error occurred.
```

/var/log/pritunl.log shows no error message, only -:

```
[undefined][2015-06-25 14:09:30,822][INFO] Generating server ssl cert
[undefined][2015-06-25 14:09:37,273][INFO] Starting setup server
[undefined][2015-06-25 14:10:28,729][INFO] Setting db version
  new_ver = '1.3.651.28'
  cur_ver = '1.3.651.28'
[undefined][2015-06-25 14:10:28,821][INFO] Changing administrator password
  username = 'pritunl'
[undefined][2015-06-25 14:10:28,821][INFO] Generating auth token
[undefined][2015-06-25 14:10:28,822][INFO] Generating auth secret
```

iptables -L -n shows an accept rule for pritunl and nothing else as this is a brand new, otherwise empty Ubuntu 14.04.2 container -:

```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            /* pritunl_012345678901234567891234 */
                                                                                                
Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination       
```

(string after pritunl_ edited as I don't know what it is)

Any help appreciated, thank you.

**Comment by zachhuff386** [comment]
The `/var/log/pritunl.log` is used as a fallback when the database server is unavailable. By default logs will go the database server and can be view by running the command `pritunl logs` this is done to make viewing logs on all servers in an enterprise cluster possible.

**Comment by ossvirt** [comment]
Got it, thanks. It looks like it failed to make several iptables rules. One masquerade rule to join an internal subnet, and a forward rule for a tun device.

```
CalledProcessError: Command '['iptables', '-A', 'POSTROUTING', '-t', 'nat', '-d'
, u'10.160.0.0/22', '-o', 'eth0', '-j', 'MASQUERADE', '-s', u'192.168.234.0/24',
 '-m', 'comment', '--comment', 'pritunl_123...456', '--wait']' re
turned non-zero exit status 3
  output    = "iptables v1.4.21: can't initialize iptables table `nat': Table do
es not exist (do you need to insmod?)\nPerhaps iptables or your kernel needs to 
be upgraded.\n"
  server_id = ObjectId('123...456')
  rule      = ['FORWARD', '-i', 'tun19', '-o', 'eth0', '-m', 'state', '--state',
 'ESTABLISHED,RELATED', '-j', 'ACCEPT', '-m', 'comment', '--comment', 'pritunl_1
23...456', '--wait']
```

Also - are these strings of hex or whatever actually sensitive identifiers? Do I need to obfuscate them as above or not?

So there is no NAT table which is what I guess is causing the problems. I had upgraded via apt without rebooting so I just restarted the container and no change. I'm guessing it could be something to do with the OpenVZ template config so I think I will remake the guest as a qemu VM and try again.

Thanks for your help.

**Comment by zachhuff386** [comment]
The ID's in the iptables comment represent the server ID. The error above is caused by an incorrectly configured VM.
