### ISSUE TITLE
DNS stops functioning

### ISSUE THREAD

**Issue by lucasjans** [pritunl/pritunl#122]
I tried Pritunl's automated setup on DO. It worked for sometime, and then without any configuration changes the DNS stops working I can't resolve any domain names when connected. Where do I start to diagnose a problem like this?

**Comment by zachhuff386** [comment]
Check the dns settings on the client and the openvpn client. The client operating system is likely overriding to a dns server that becomes unreachable when connected to the vpn.

**Comment by lucasjans** [comment]
Thanks @zachhuff386 - I regenerated the ovpn file and it works now. But I've noticed this happening a few times across devices. I'll keep an eye on it.

Another thing I see: I cannot connect to UDP type services when the VPN is up. Slack never gets connected, for example. Is that because I'm using a UDP VPN?
