### ISSUE TITLE
Network subnet beyond /24 not being accepted

### ISSUE THREAD

**Issue by centric-jim** [pritunl/pritunl#124]
Not sure if I'm doing something wrong here, but when setting up an OpenVPN server, it does not allow a network (subnet) larger than a /24.  For example, I can do 10.45.240.0/24, but I can't do /23, /22, etc.  I get an error saying "Network address is not valid, format must be "[10,172,192].[0-255,16-31,168].[0-255].0/[8-24]" such as "10.12.32.0/24".

**Comment by zachhuff386** [comment]
Only 8, 16 and 24 are usable, there is more info on the available subnets in the wiki https://github.com/pritunl/pritunl/wiki/Server
