### ISSUE TITLE
Ongoing installation issues

### ISSUE THREAD

**Issue by ossvirt** [pritunl/pritunl#125]
Problems with a new install that I mentioned in a previous issue post [MongoDB not starting](https://github.com/pritunl/pritunl/issues/123) are still ongoing.

Can I ask you to tell me the necessary steps to install Pritunl on a new, blank Ubuntu Server 14.04.2 64 with only SSH server selected from Tasksel. I updated, upgraded and rebooted the box before installing the Pritunl PPA and it still can't start MongoDB.

Many thanks for your help with this, I am looking forward to running Pritunl.

**Comment by zachhuff386** [comment]
I've tested 14.04 packages there isn't any issues.

**Comment by Y4Rv1K** [comment]
Have this issue at 15.10
