### ISSUE TITLE
Please update API Documentation

### ISSUE THREAD

**Issue by centric-jim** [pritunl/pritunl#129]
Hi there,

I'm trying to convince my company to pay for PriTunl since I think you're onto a great start.  Could you _please_ update your API documentation with a working example of how to use the API?

Under Authentication, https://pritunl.com/api.html#authentication, in your doc you say something about, "Below is an example wrapper function to sign API requests." But there is no example.  Below that you list what headers are to be used:
Header Parameters
Auth-Token 	API token
Auth-Timestamp 	Epoch timestamp must be accurate to +/-5 minutes of server time
Auth-Nonce 	Random alphanumeric string of 32 characters must be unique for each request
Auth-Signature 	Base64 digest of hash signing algorithm

What does, "Base64 digest of hash signing algorithm" mean in this context.  We don't understand how "Auth-Signature" is to be created, what it's based on?  Is it a combination of the username:password?  Is it a hash of the API Secret?  For the Base64 hashing are you using HMAC, MD5, SHA, SHA-256?  To be honest we've go folks who've wasted the better part of a day trying to decipher how how this is to be done.

Even a simple cURL example with the -d headers would be sufficient.  Sorry to be a PITA, but we're in crunch mode.

**Comment by zachhuff386** [comment]
A Javascript error was causing the api examples to not render, it is fixed now. The pages may take a few minutes to update on github pages.
