### ISSUE TITLE
User / Certificate expiry date

### ISSUE THREAD

**Issue by jamesarems** [pritunl/pritunl#130]
Hi Team,

Im loving with this project and implemented in my lab. I have a request , i think its a needed one.
1) User / Client certificate expiry date settings
2) Option for clean recent log entries from Dashboard.

Regards and best of luck

**Comment by 4b3ldu4rt3** [comment]
we could specify to allow logins without date control

if a client has his clock set wrongly it could log in to server the same way

**Comment by scriby** [comment]
I've also wanted to be able to set custom expiry settings on the generated certificates
