### ISSUE TITLE
production server

### ISSUE THREAD

**Issue by phirestalker** [pritunl/pritunl#133]
I am on osx 10.10.4 and want to know how to turn what I downloaded from git into a production server, so I don't have to start the vagrant profiles and inside start the pritunl server manually. I go to the main website and the only instructions are to set it up on some cloud server, or on linux. Thanks

**Comment by zachhuff386** [comment]
The code on git cannot be used for production. The vagrant machines were also recently removed from the repo.

**Comment by phirestalker** [comment]
is there any way to get pritunl running on mac other than the depreciated vagrant I have now?
