### ISSUE TITLE
Pritunl allways gives the same virtual ip to all users....

### ISSUE THREAD

**Issue by EnZoSix** [pritunl/pritunl#135]
i have multiple users all from different ip's but when i turn pritunl ON appears in server output this MULTI_sva: pool returned IPv4=192.168.245.2
all recive the same virtual ip... Why, can someone explain to me what happen...

**Comment by EnZoSix** [comment]
i really need to know why all external ip's recive the same virtual ip at the server Log

Exemple:
215.119.124.122:49568 MULTI_sva: pool returned IPv4=192.168.245.2, IPv6=......
84.254.145.24:53102 MULTI_sva: pool returned IPv4=192.168.245.2, IPv6=.....

**Comment by EnZoSix** [comment]
??? any help?

**Comment by EnZoSix** [comment]
????

**Comment by zachhuff386** [comment]
I haven't been able to reproduce this issue and the information above isn't detailed enough to determine what the issue is.
