### ISSUE TITLE
Restricting client to client communication

### ISSUE THREAD

**Issue by cmillosh** [pritunl/pritunl#138]
Can you add in the feature to where a client can't see or communicate with another client on a different server.

For instance user1 is on vpnserver1 and user2 is on vpnserver2 each with different subnets being assigned.  I would like it that user1 couldn't communicate with user2.

If it's already built in I can seem to find it.

Thanks,
Carl

**Comment by zachhuff386** [comment]
This is available with connected servers in the Enterprise subscription.

**Comment by cmillosh** [comment]
Well that make the subscription much more enticing. let me be clear.  I can have multiple servers on one instance, and assign different subnets to "clients".  Is this feature only available on physical boxes or from each server I setup on a box?

For instance if I have vpn servers setup in the US, FR, UK, RU, CA, etc.  Can the clients talk within each realm?  For instance can all the US clients see each other, but not see FR?  I'm asking that each realm(server's) users can't see each other.  And when I reference servers I reverence servers as setup in PriTunl, not physical boxes.

Thanks,
Carl

**Comment by zachhuff386** [comment]
I didn't fully read the first comment, the deleted response was about connected servers which allow connecting multiple servers across different instances. Allowing clients connected to one of the servers to access all of the subnets available on the connected servers. Restrictions for communication between vpn subnets on the same instance would need to be done manually.

**Comment by cmillosh** [comment]
Okay, thanks for the clarification, I think I can accomplish my goals by using containers to separate everything out versus subnets on an instance.  I'll do some testing and let you know.

Thanks for your replies and you've done some good work!!!
