### ISSUE TITLE
pritunl not connecting to MongoDB when it runs as a service

### ISSUE THREAD

**Issue by MLWALK3R** [pritunl/pritunl#139]
When MongoDB is running as a background service pritunl will not connect to it, I have to stop the service then start it manually (root@host:~# mongod ) for it to connect.

**Comment by zachhuff386** [comment]
What distro/release are you using?

**Comment by MLWALK3R** [comment]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"

**Comment by MLWALK3R** [comment]
Fix is to change 
```
mongodb://localhost:27017/pritunl >> mongodb://127.0.0.1:27017/pritunl
```
