### ISSUE TITLE
RAM Usage for Pritunl

### ISSUE THREAD

**Issue by centric-jim** [pritunl/pritunl#140]
Is 25G (VIRT) and 9GB RES (used) normal?  

Tasks: 135 total,   4 running, 131 sleeping,   0 stopped,   0 zombie
%Cpu(s): 49.5 us, 13.6 sy,  0.0 ni, 36.4 id,  0.4 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem :  1884812 total,   302220 free,  1326972 used,   255620 buff/cache
KiB Swap:  4095996 total,  3499176 free,   596820 used.   334908 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                                            
11747 root      20   0 25.851g 988204   1552 S 80.0 52.4   1396:08 pritunl                                                                                                                                            
11533 mongod    20   0  719968  69560   9924 R  5.0  3.7 148:56.17 mongod

**Comment by zachhuff386** [comment]
I haven't seen any memory leaks or memory related issues on test servers. Check for excessive `openssl` processes running.
