### ISSUE TITLE
/8, /16, or /24 Subnet Limitation

### ISSUE THREAD

**Issue by centric-jim** [pritunl/pritunl#141]
Hello,

Wanted to revisit the rational for limiting VPN subnets to /8, /16, or /24.  I've run OpenVPN servers in the past and had no issues setting arbitrary CIDR subnets (for example /26 to /21 subnets).  This is an issue for us because we have about 500 vpn clients connecting, which necessitates our using a /16 subnet, and we have a tool (Goverlan) which has to scan the entire /16 to 'find' clients connected to OpenVPN, that's 65,534 IPs, and that takes a _long_ time to complete.

**Comment by zachhuff386** [comment]
The subnet limitations will be removed in a future release, there is still some testing with different subnets that needs to be done.

**Comment by aidanjl** [comment]
Has this been fixed in the current release?

**Comment by zachhuff386** [comment]
All subnets are now supported

**Comment by aidanjl** [comment]
Great, thank you!
