### ISSUE TITLE
Per Client Server Mode

### ISSUE THREAD

**Issue by benmaynard11** [pritunl/pritunl#142]
It would be good to be able to set a per-client server mode. At the moment the only option we have is to set the server mode for all clients. However this causes an issue in the following scenario:

I want to create an intranet for my users. I want all of my users traffic to go through the VPN server so that it is secured. 

I also want to add servers to this network to provide various different services on the intranet. However, with the current way Pritunl works, I would have to send all of the traffic from my servers through the VPN too, and not just the specific subnets that I want. In a datacenter, this would mean all the traffic from every server going through this server....

**Comment by zachhuff386** [comment]
There isn't any plans to add additional per-client settings.
