### ISSUE TITLE
Multipule Network Routing

### ISSUE THREAD

**Issue by darksheer** [pritunl/pritunl#144]
A server with multiple interfaces all with appropriate routes setup is not routing traffic properly.  It looks like Pritunl only puts one route into the routing table (gw 0.0.0.0)--is this expected behavior? Is there a way to configure static routes within pritunl?

Thx,

Vince

**Comment by zachhuff386** [comment]
To add routes to the vpn server set the `Server Mode` to `Local Traffic Only` and add the networks to `Local Networks`. A route of `0.0.0.0` would indicate the server is in `All Traffic` mode.
