### ISSUE TITLE
having problems with "Allow Multiple Devices"

### ISSUE THREAD

**Issue by comsyspro** [pritunl/pritunl#151]
Hi,

when I activate the option `Allow Multiple Devices` and connecting two clients with the same client.ovpn (same common name) then the first of them get an ip address and the second tries to get an ip address but fails to start properly. Normally the `Allow Multiple Devices ~ duplicate-cn` should accept the connection with only one unique user config file and the server should give every client a different ipaddress. What's the problem here?

**Comment by zachhuff386** [comment]
The line `setenv UV_ID UUID` in the conf should be unique to each connecting client. When using multiple devices the client conf should be downloaded from the Pritunl server separately for each client to allow the Pritunl server to generate a different `UV_ID` and `UV_NAME`.
