### ISSUE TITLE
Wishlist and testing result

### ISSUE THREAD

**Issue by sl-ll** [pritunl/pritunl#152]
Hi,
I'm using your cool application and I'd like to put it in production. But there are next points that would be good to have in the future.

1) "Pritunl VPN-Key" message: That would be good to be able to edit it. (Put some instructions for users etc) Maybe for now that can be done manually in some template?
2) iptables. You use NAT that is fine for me. But I'd like to have access rules per user and per organisation. That is now so urgent cause I still can make iptables rules at the INUT chain manually.
3) I'd like to set ip-addresses for users manually. For now I did update mongodb-record manually but after I changed server network from WebUI all network reservation became broken.
4) In mongodb I see much more records in server_ip_pool then I have in users collection

**Comment by adumont** [comment]
@sl-ll How did you address 3) right now?

**Comment by MichaelAndoid** [comment]
I loved to see all that wish list implemented

**Comment by sl-ll** [comment]
@adumont Now I'm using default dynamic addressing provided by pritunl - client first connected and get next IP from subnet. But for some client I need direct IP and there's no chance to do this from web-interface. So I made workaround and update db-record manually in mongo and that works my client received address I want.

**Comment by zachhuff386** [comment]
There isn't any significant use cases for these features and the features will likely never be added.
