### ISSUE TITLE
<%= version %> bug Changelog

### ISSUE THREAD

**Issue by MichaelAndoid** [pritunl/pritunl#153]
I dont now what is the last version build, because in change log show this. and i know the last is not Version 1.3.662.15 2015-07-06
####################################

<%= version %>

Add support for bridge mode
Add support for Chromebook
Add ssl cert to settings
Fix issue with multiple clients
Fix issue with utf-8 names
Add support for all private subnets for server network
Change database format requires db upgrade
Remove upgrade support for 0.10.x

Version 1.3.662.15 2015-07-06

**Comment by zachhuff386** [comment]
That indicates an unreleased version with a list of changes that will be in the next release `1.3.662.15` is the last stable release. Snapshot dev releases are not shown in the changelog.
