### ISSUE TITLE
Force update to pritunl v1.4.722.95

### ISSUE THREAD

**Issue by MichaelAndoid** [pritunl/pritunl#154]
Wen i try to make update to ptitunl dont show the last pritunl.
I do this:
apt-get update 
apt-get upgrade

And after i check the version installed:
dpkg -s pritunl
Version: 1.3.662.15-0ubuntu1~trusty

Iam running Ubuntu 14.04 x32, and i dont now how to force update to the last version!

**Comment by zachhuff386** [comment]
The repo was move from launchpad you will need to use the new repo to upgrade. First remove the ppa `add-apt-repository --remove ppa:pritunl` then use the instructions on the homepage.
