### ISSUE TITLE
Failed to start server after upgrade configuration to bridge mode

### ISSUE THREAD

**Issue by sl-ll** [pritunl/pritunl#156]
Hi, yesterday I upgraded pritunl to new version and reconfigure one of the servers to use bridge mode.

First fail was "ERROR Failed to find bridged network interface"  so pritunl does not configured bridge (I hoped)
After that I put configuration back to tunnel mode and on one of the cluster hosts pritunl.service won't start

 /usr/lib/pritunl/bin/pritunl start --daemon --pidfile /var/run/pritunl.pid
Traceback (most recent call last):
  File "/usr/lib/pritunl/bin/pritunl", line 9, in <module>
    load_entry_point('pritunl==1.4.722.95', 'console_scripts', 'pritunl')()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/__main__.py", line 119, in main
    from pritunl import settings
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/settings/__init__.py", line 5, in <module>
    sys.modules[__name__] = Settings()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/settings/settings.py", line 24, in __init__
    self._init_modules()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/settings/settings.py", line 106, in _init_modules
    group_cls.load()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/settings/group_file.py", line 26, in load
    name, value = line.split('=', 1)
ValueError: need more than 1 value to unpack

And for other two hosts in cluster I see next message on server start

[vpn4-int-v] Options error: In [CMD-LINE]:1: Error opening configuration file: /tmp/pritunl_32f4d2365e434ca1b8d9acd1007b28bd/087142b9d455405cade631eb8ec6cfbe/openvpn.conf
[vpn4-int-v] Use --help for more information.
[vpn3-int-v] Options error: In [CMD-LINE]:1: Error opening configuration file: /tmp/pritunl_9ecf27228d70424292350aae29e2dd55/6754909955314192975aea703ebbbcce/openvpn.conf
[vpn3-int-v] Use --help for more information.

It does not create subdir and conf-file

I can repeat all steps from the begin, but I had this issue already on dev version before it get stable

**Comment by zachhuff386** [comment]
The bridge network must match the network of one of the network interfaces on the server.

The second error is from invalid json in your configuration file, the original error was shadowed from some 0.10.x upgrade code. Check that the file `/etc/pritunl.conf` has valid json.

The third error isn't detailed enough, it could be a permission error.

**Comment by sl-ll** [comment]
If I greped right 
/usr/lib/pritunl/lib64/python2.7/site-packages/pritunl/server/instance_link.py

    def generate_client_conf(self):
        if not os.path.exists(self._temp_path):
            os.makedirs(self._temp_path)
        ovpn_conf_path = os.path.join(self._temp_path, OVPN_CONF_NAME)

os.makedirs(path[, mode]) what mode should be ??

because _temp_path dos not contains subdirs and openvpn.conf file

ls -l /tmp/pritunl_280fc357f7704b348ef7427a1696d37c/
total 8
-rw-r--r--. 1 root root 1910 Sep  8 13:06 server.crt
-rw-------. 1 root root 3267 Sep  8 13:06 server.key

and in server log the first part /tmp/pritunl_280fc357f7704b348ef7427a1696d37c/ (755) is const and the variable part does not created

root     15252  Sl   13:06   0:40 /usr/lib/pritunl/bin/python2 /usr/lib/pritunl/bin/pritunl start --daemon

**Comment by zachhuff386** [comment]
The code above wouldn't be related to the issue. Look for the full log output by running the command `pritunl logs`

**Comment by sl-ll** [comment]
[vpn2-int-v][2015-09-08 13:37:31,525][ERROR] Server management socket path not found
  instance_id = ObjectId('55eec85f91643b3b9404631d')
  socket_path = '/var/run/pritunl_55eec85f91643b3b9404631d.sock'
  server_id   = ObjectId('55df1a1091643b0b7a01104e')
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 784, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 199, in _socket_thread
    self.connect()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 244, in connect
    self.wait_for_socket()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 150, in wait_for_socket
    socket_path=self.socket_path,
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 56, in error
    kwargs['traceback'] = traceback.format_stack()
[vpn2-int-v][2015-09-08 13:37:31,974][INFO] Failed to find interface for local network route, using default route
  server_id = ObjectId('55df1a1091643b0b7a01104e')
[vpn2-int-v][2015-09-08 13:37:31,975][INFO] Failed to find interface for local network route, using default route
  server_id = ObjectId('55df1a1091643b0b7a01104e')


nothing about /tmp/pritunl_*

**Comment by zachhuff386** [comment]
Moving all information for error "Server stopped unexpectedly" to #158
