### ISSUE TITLE
Several small bugs

### ISSUE THREAD

**Issue by grikster** [pritunl/pritunl#157]
- On Dashboard Users online count is always 0, when you go tu Users you can see them connected.
- Rebooting server changes the VPN IP address of users, that shouldnt happend, the IP should be fixed after first connect.
- Also the Server stopped unexpectedly, is happening 2 or 3 times a day, without any reason, only 4 users online atm.

Using CentOS7 64, clean install.

Some good things, this 1.4 version is faster connect and showing results than the previous 1.3. Good work!

**Comment by zachhuff386** [comment]
Are the user ip address of connected users changing or the ip address shown when the users are disconnected.

Check the out of `pritunl logs` for the server stopping.

**Comment by zachhuff386** [comment]
Moving all information for error "Server stopped unexpectedly" to #158

**Comment by grikster** [comment]
Visual bug i confirmed the users on dashbord show 0 and users are connected
green under Users.
The other bug maybe is related, on Users they all go RED offline, but they
are connected, and when they come back Green Online, the VPN IP changed.
192.168.200.xx.


The other server stopped buy im attaching full log here
Running "pritunl logs" shows some errors, maybe it can help you.

*XEN VPS CentOS7 64 fully updated and fresh install*. Only installed
pritunl, nothing more


[root@user log]# pritunl logs
> [evening-thunder-8838][2015-09-07 12:52:23,875][INFO] Starting server
> [evening-thunder-8838][2015-09-07 12:52:54,047][INFO] Changing
> administrator password
>   username = u'fvasssmin'
> [evening-thunder-8838][2015-09-07 12:54:08,469][INFO] Changing
> administrator password
>   username = u'fvasssmin'
> [evening-thunder-8838][2015-09-07 14:40:46,455][INFO] Starting server
> [evening-thunder-8838][2015-09-07 17:22:10,108][ERROR] Error parsing
> client connect
> Traceback (most recent call last):
>   File
> "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/clients.py",
> line 189, in connect
>     self.instance_com.send_client_auth(client, client_conf)
>   File
> "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/instance_com.py",
> line 44, in send_client_auth
>     client['client_id'], client['key_id'], client_conf))
> error: [Errno 32] Broken pipe
>   server_id = ObjectId('55ed898139fb55038f7b5ec7')
> [evening-thunder-8838][2015-09-07 17:22:10,408][ERROR] Failed to parse
> line from vpn com
> Traceback (most recent call last):
>   File
> "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/instance_com.py",
> line 224, in _socket_thread
>     self.parse_line(line)
>   File
> "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/instance_com.py",
> line 74, in parse_line
>     self.clients.connect(self.client)
>   File
> "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/clients.py",
> line 198, in connect
>     client, 'Error parsing client connect')
>   File
> "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/instance_com.py",
> line 48, in send_client_deny
>     client['client_id'], client['key_id'], reason))
> error: [Errno 32] Broken pipe
>   instance_id = ObjectId('55edb98c39fb5501ee79bac9')
>   server_id   = ObjectId('55ed898139fb55038f7b5ec7')
>   line        = '>CLIENT:ENV,END'
> [evening-thunder-8838][2015-09-07 17:22:10,460][ERROR] Error parsing
> client connect
> Traceback (most recent call last):
>   File
> "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/clients.py",
> line 135, in connect
>     self.instance_com.client_kill(device)
>   File
> "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/instance_com.py",
> line 38, in client_kill
>     self.sock.send('client-kill %s\n' % client['client_id'])
> error: [Errno 32] Broken pipe
>   server_id = ObjectId('55ed898139fb55038f7b5ec7')
> [evening-thunder-8838][2015-09-07 17:22:10,461][ERROR] Failed to parse
> line from vpn com
> Traceback (most recent call last):
>   File
> "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/instance_com.py",
> line 224, in _socket_thread
>     self.parse_line(line)
>   File
> "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/instance_com.py",
> line 74, in parse_line
>     self.clients.connect(self.client)
>   File
> "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/clients.py",
> line 198, in connect
>     client, 'Error parsing client connect')
>   File
> "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/instance_com.py",
> line 48, in send_client_deny
>     client['client_id'], client['key_id'], reason))
> error: [Errno 32] Broken pipe
>   instance_id = ObjectId('55edb98c39fb5501ee79bac9')
>   server_id   = ObjectId('55ed898139fb55038f7b5ec7')
>   line        = '>CLIENT:ENV,END'
> [evening-thunder-8838][2015-09-08 08:06:19,364][ERROR] Server management
> socket path not found
>   instance_id = ObjectId('55ee88d039fb5501ee7a54b8')
>   socket_path = '/var/run/pritunl_55ee88d039fb5501ee7a54b8.sock'
>   server_id   = ObjectId('55ed898139fb55038f7b5ec7')
> Traceback (most recent call last):
>   File "/usr/lib64/python2.7/threading.py", line 784, in __bootstrap
>     self.__bootstrap_inner()
>   File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
>     self.run()
>   File "/usr/lib64/python2.7/threading.py", line 764, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File
> "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/instance_com.py",
> line 199, in _socket_thread
>     self.connect()
>   File
> "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/instance_com.py",
> line 244, in connect
>     self.wait_for_socket()
>   File
> "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/instance_com.py",
> line 150, in wait_for_socket
>     socket_path=self.socket_path,
>   File
> "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/logger/__init__.py",
> line 56, in error
>     kwargs['traceback'] = traceback.format_stack()
> [root@user log]#


If any personal info on quote, please delete. Hope this helps

Thanks great work!

**Comment by zachhuff386** [comment]
The status page issue was fixed in the commit above it wouldn't cause any of the other issues. The errors above are likely from the vpn process unexpectedly. What is the output of `free -h`?

**Comment by grikster** [comment]
On Tue, Sep 8, 2015 at 5:44 PM, Zachary Huff <notifications@github.com>
wrote:

> free -h


[root@user ~]# free -h
              total        used        free      shared  buff/cache
available
Mem:           989M        109M        523M         49M        356M
 806M
Swap:          511M          0B        511M


More Info:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.1.1503 (Core)
CentOS Linux release 7.1.1503 (Core)

**Comment by zachhuff386** [comment]
The swap is full and little memory is available check `top -o %MEM` to see if any `pritunl`, `openvpn` or `openssl` processes are using alot of memory.

**Comment by grikster** [comment]
>
>
> [root@user ~]# top -o %MEM
> +
> top - 17:52:39 up 1 day,  3:12,  1 user,  load average: 0.00, 0.01, 0.05
> Tasks:  70 total,   1 running,  69 sleeping,   0 stopped,   0 zombie
> %Cpu(s):  0.9 us,  0.5 sy,  0.0 ni, 98.2 id,  0.0 wa,  0.0 hi,  0.2 si,
>  0.2 st
> KiB Mem :  1013236 total,   534232 free,   113296 used,   365708 buff/cache
> KiB Swap:   524284 total,   524284 free,        0 used.   825068 avail Mem
>   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
>   494 root      20   0 1455748  43116   3296 S   2.7  4.3  30:43.55 pritunl
>   641 mongodb   20   0  645840  39792   6112 S   9.0  3.9 111:22.02 mongod
> 12480 root      20   0  135216   5260   4072 S   0.0  0.5   0:00.06 sshd
>  4947 root      20   0   52836   4400   3044 S   0.0  0.4   0:12.24 openvpn
>   334 root      20   0  318172   4360   3616 S   0.0  0.4   0:10.09
> rsyslogd
>   708 postfix   20   0   91256   3892   2900 S   0.0  0.4   0:00.11 qmgr
> 12105 postfix   20   0   91188   3876   2884 S   0.0  0.4   0:00.01 pickup
>     1 root      20   0   54124   3732   2408 S   0.0  0.4   0:03.10 systemd
>   597 root      20   0   82508   3612   2760 S   0.0  0.4   0:07.32 sshd
>   237 root      20   0   41160   2912   2616 S   0.0  0.3   0:34.58
> systemd-jo+
>   697 root      20   0   91084   2156   1128 S   0.0  0.2   0:00.52 master
>   257 root      20   0   42088   1896   1220 S   0.0  0.2   0:00.10
> systemd-ud+
> 12484 root      20   0   11744   1876   1492 S   0.0  0.2   0:00.02 bash
>   264 root      16  -4  116708   1704   1320 S   0.0  0.2   0:07.63 auditd
>   341 root      20   0   34684   1652   1348 S   0.0  0.2   0:00.13
> systemd-lo+
> 12854 root      20   0   24216   1552   1136 R   0.0  0.2   0:00.01 top
>   747 root      20   0   22720   1520    904 S   0.0  0.2   0:00.41 crond



Here it is, i have only 3 connected clients and 10 users created.

A friend of mine is testing he says exactly that OpenVPN starts sonsuming
alot of memory and it crashes, thats whats probably happening

**Comment by zachhuff386** [comment]
The last commit may fix the issue. There was a missing lock for the socket making it possible in some scenarios for the server to write to the socket from two threads at the same time.

**Comment by zachhuff386** [comment]
I was able to reproduce the error with the current release. After testing with the last commit it hasn't happened so it's likely the cause. If you want to test the last commit run `systemctl stop protinl` copy the code from https://raw.githubusercontent.com/pritunl/pritunl/master/pritunl/server/instance_com.py and run `rm /usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/instance_com.py; nano /usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/instance_com.py` then paste it in the file. Then run `systemctl start pritunl`

**Comment by grikster** [comment]
Perfect ! Im glad i could help.

I cant do that for now, i will wait for the update just because some VPN
clients need to use it and me playing with it will be bad for them.

Tell me if you need future logs or anything, i can run and give you outputs.

Good work !!


Frederico Valério

**Comment by grikster** [comment]
The update you did today, now after cache clean, update and rebooting
server, gets me this error on logs


[root@vm2617 ~]# pritunl logs --limit=1000
> [evening-waterfall-3651][2015-09-09 10:11:45,436][INFO] Starting server
> [evening-waterfall-3651][2015-09-09 10:12:10,374][INFO] Changing
> administrator password
>   username = u'fvalerioadmin'
> [evening-waterfall-3651][2015-09-09 18:12:52,009][ERROR] Failed to check
> notifications
> Traceback (most recent call last):
>   File
> "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/runners/updates.py",
> line 22, in _check_updates
>     response = urllib2.urlopen(request, timeout=60)
>   File "/usr/lib64/python2.7/urllib2.py", line 127, in urlopen
>     return _opener.open(url, data, timeout)
>   File "/usr/lib64/python2.7/urllib2.py", line 404, in open
>     response = self._open(req, data)
>   File "/usr/lib64/python2.7/urllib2.py", line 422, in _open
>     '_open', req)
>   File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain
>     result = func(*args)
>   File "/usr/lib64/python2.7/urllib2.py", line 1224, in https_open
>     return self.do_open(httplib.HTTPSConnection, req)
>   File "/usr/lib64/python2.7/urllib2.py", line 1186, in do_open
>     raise URLError(err)
> URLError: <urlopen error [Errno -2] Name or service not known>
> [evening-waterfall-3651][2015-09-09 22:14:07,978][ERROR] Failed to check
> notifications
> Traceback (most recent call last):
>   File
> "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/runners/updates.py",
> line 22, in _check_updates
>     response = urllib2.urlopen(request, timeout=60)
>   File "/usr/lib64/python2.7/urllib2.py", line 127, in urlopen
>     return _opener.open(url, data, timeout)
>   File "/usr/lib64/python2.7/urllib2.py", line 404, in open
>     response = self._open(req, data)
>   File "/usr/lib64/python2.7/urllib2.py", line 422, in _open
>     '_open', req)
>   File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain
>     result = func(*args)
>   File "/usr/lib64/python2.7/urllib2.py", line 1224, in https_open
>     return self.do_open(httplib.HTTPSConnection, req)
>   File "/usr/lib64/python2.7/urllib2.py", line 1186, in do_open
>     raise URLError(err)
> URLError: <urlopen error timed out>
> [winter-skies-8075][2015-09-10 15:01:03,632][INFO] Starting server
> [root@vm2617 ~]#


It wasent making any error the previous version

Just to keep you posted.

Thanks

**Comment by zachhuff386** [comment]
That error won't cause any issues it's only an update check.

**Comment by grikster** [comment]
This version uses less cache, the previous was using 800 MB cache. But i
didnt reboot then, maybe that was making a diference. Now the Free memory
is really Free and not in cache.
Maybe its nothing but just keeping you posted.


[image: Inline image 1]

**Comment by grikster** [comment]
Same bug still hapenning in today Update (Fix connectivity display issues)
but its still happening.
The update was made after the cache cleaned command.

The Users go ZERO after a while and in the Users Tab they are all RED
Offline, but in reality they are Online.

It happens 10 min after for some, for me it took some hours to happen and
only in this latest update, but some members reported also in the previous
1.4 versions, all of them.

**Comment by zachhuff386** [comment]
Yeah I found that issue while testing I've made some changes and I'm testing it now. Should be updated later tonight.

**Comment by grikster** [comment]
Not seeing any problems on this latest version, but ill keep you posted.

Another thing:
Is it possible to make a Manual to backup the bd and restore properly.
Users have having problem restoring to 1.4 from 1.3.
Could you be so kind to lend some light on the correct way to backup and to
restore. To avoid having to change every certificate in every machine.

Thank You
I know have an extra VPS if you need me i can test stuff for you.

**Comment by grikster** [comment]
Hello again,

another small bug i think.

When Clicking on Restart Server on Pritunl ControlPanel the VPN clients
change VPN Address, this is not good is there a way or a new option you can
deliver to make the IP always on that machine?
When i reboot the VPS the IPs dont change, only if i reboot inside Pritunl
CP Servers menu.


Thanks again

**Comment by zachhuff386** [comment]
What are you referring to by vpn address, the clients virtual ip address, clients real ip address or the vpn server connection address?

**Comment by grikster** [comment]
Virtual IP address - 192.168.2xx.y

Y change when on Pritunl CP Servers button Restart.
If I reboot the whole VPS they don't change.

Can you test on your system?

Thanks

No dia domingo, 13 de setembro de 2015, Zachary Huff <
notifications@github.com> escreveu:

> What are you referring to by vpn address, the clients virtual ip address,
> clients real ip address or the vpn server connection address?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pritunl/pritunl/issues/157#issuecomment-139873106>.
>


-- 
Cumprimentos
Frederico Valério
914528499

**Comment by zachhuff386** [comment]
Do you have multiple devices enabled and what is the output of `pritunl version`

**Comment by 4b3ldu4rt3** [comment]
with multiple devices that happens
pritunl gives new ip adress to client even on old on

example
client logs with IP x
if we restar on pritunl panel  that client gets ip y and z (never x that it was is original IP)

**Comment by 4b3ldu4rt3** [comment]
how to make upgrade to pritunl ONLY on ubuntu but not deleting users etc etc

this week I have lost all my clients and server settings
