### ISSUE TITLE
[Question] 7 day trial - How to activate it?

### ISSUE THREAD

**Issue by Esya** [pritunl/pritunl#159]
Hi,

We just deployed pritunl to one of our servers and when I click on `Upgrade to premium` I see a 7 day trial option for both plans. But it is not clickable, I do not have a promo code nor a license, and when I click "Get Entreprise 50$/month" I only get the stripe payment form. 

Am I missing something here? If so, how can we actually try the entreprise plan for a few days?

Thanks

**Comment by zachhuff386** [comment]
The trial is automatic after starting a subscription the credit card won't get charged until the trial has ended.
