### ISSUE TITLE
Pusing custom routes

### ISSUE THREAD

**Issue by lucasjans** [pritunl/pritunl#162]
I live in Vietnam but often need to have a fast connection to US servers. If I route my traffic to a specific provider I get amazing speeds. But I only wish to route traffic that's destined to the US to this VPN. In a typical OpenVPN connection I can specify the list of hosts with the push-route option.

The list is here - it's huge!
http://www.iwik.org/ipcountry/US.cidr

What's the best way to configure Pritunl to handle these custom routes - in a performant way? Is it crazy to add thousands of entries to the route table?

**Comment by zachhuff386** [comment]
The local network routing isn't intended for that, it could  be done client side or by editing the conf in constants.

**Comment by lucasjans** [comment]
Thanks Zach. Will try client side editing first.
