### ISSUE TITLE
scramble all the data in the packet 

### ISSUE THREAD

**Issue by k0tkin** [pritunl/pritunl#163]
Hi,

This project is really amazing, I think it'll be more better if you add new feature like scrambling all the data in the packet for each server, here is more info:
https://forums.openvpn.net/topic12605.html
http://www.lowendtalk.com/discussion/21539/tutorial-build-your-ultimate-scrambled-vpn

**Comment by zachhuff386** [comment]
There isn't any significant use cases for this feature and it will likely never be added.
