### ISSUE TITLE
Only one device with one user on all servers

### ISSUE THREAD

**Issue by k0tkin** [pritunl/pritunl#164]
Hi,

I have plan to use pritunl to sell OpenVPN service but i have a problem
I have 100 server 
I need each user be able to login on one server at each time 
But right now if user1 is connected to (for example) server12 with device1 another device is able to connect to (for example) server37 with user1 credential

**Comment by zachhuff386** [comment]
The license doesn't allow this https://github.com/pritunl/pritunl/blob/master/LICENSE
