### ISSUE TITLE
Sync configs with clients

### ISSUE THREAD

**Issue by 4b3ldu4rt3** [pritunl/pritunl#167]
DOnt know if implemented but.. is there an option to sync with clients conf file if we change any parameter on server?

for example if I use now realIP and I change to dns.org... server would update every client on logon!
as this any other option...that would request client update!

**Comment by 4b3ldu4rt3** [comment]
enhancement

**Comment by zachhuff386** [comment]
Configuration sync is available with Premium and Enterprise when using the Pritunl client.

**Comment by 4b3ldu4rt3** [comment]
so I have premium... if I change my settings from IP to DNS.. all clients will be updated?

**Comment by zachhuff386** [comment]
Yes all settings will sync

**Comment by 4b3ldu4rt3** [comment]
thanks. will test and report. will define dns on server and see if clients conf gets updated

**Comment by 4b3ldu4rt3** [comment]
rebooted client... 
rebooted server

clients dont get updated

I seen on client side this in log
Mon Sep 21 15:22:42 2015 Options error: Unrecognized option or missing parameter(s) in [PUSH-OPTIONS]:9: ip-win32 (2.3.4)

**Comment by zachhuff386** [comment]
I've tested conf sync don't see any issues. What option are you changing? If it's "DNS Server" that option is not stored in the conf file.

**Comment by 4b3ldu4rt3** [comment]
example
I had my setings using real IP
I changed my IO to my dns..,.. so techincally all clients shoulçd get updated on login... correct?
but it doesn't..

**Comment by 4b3ldu4rt3** [comment]
I'm referring to REMOTE field on .ovpn file
