### ISSUE TITLE
Setup hang during generating ssl cert

### ISSUE THREAD

**Issue by nikos9742** [pritunl/pritunl#170]
Hi everyone, 
I'm a student who use this wonderful app to secure my public wifi connection.
I had it installed on an EC2 ubuntu instance and it was running great for weeks but recently i wanted to reinstall a new release on a brand new instance.
I've tried many times but i always encouter this bug :

root@PritUnlTest:~# cat /var/log/pritunl.log
[undefined][2015-09-24 02:57:18,660][INFO] Starting setup server
[undefined][2015-09-24 02:57:18,661][INFO] Generating setup server ssl cert

The process seems to hang there and doesn't want to go forward.

Am I missing something ?

**Comment by zachhuff386** [comment]
The server is waiting for the initial setup.
