### ISSUE TITLE
Offer two factor authentication via DuoSecurity

### ISSUE THREAD

**Issue by henry-spanka** [pritunl/pritunl#171]
Hey,
it would be nice, if the Pritunl client would offer two factor authentication via Duo Security.
DuoSecurity already offers support for OpenVPN but it's not the best UI/method. Would really appreciate a nice UI in the Pritunl client.

Documentation:
https://www.duosecurity.com/docs/openvpn
https://github.com/duosecurity/duo_client_python

Best regards
Henry Spanka

**Comment by zachhuff386** [comment]
Duo authentication was added in 1.5 and is available with an Enterprise subscription.

**Comment by henry-spanka** [comment]
Oh, I'm sorry. Just saw it on your webpage.

Nevermind ;)
