### ISSUE TITLE
How to update Pritunl?

### ISSUE THREAD

**Issue by benmaynard11** [pritunl/pritunl#174]
Hi,

How do I update Pritunl? Also, I have this when running apt-get update

https://ray465b.images.uk.maynardnetworks.com/4c9edd38b607801ba350e49dcef963d7.png

**Comment by MLWALK3R** [comment]
```
$ nano /etc/apt/sources.list.d/pritunl.list
deb http://repo.pritunl.com/stable/apt trusty main

$ apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv CF8E292A

$  apt-get update; apt-get upgrade -y apt-get dist-upgrade
```

**Comment by benmaynard11** [comment]
Still getting this unfortunately. https://ray465b.images.uk.maynardnetworks.com/7d68043025dcb1b5c7edc801763a5aeb.png

**Comment by MLWALK3R** [comment]
Remove the old repo form /etc/apt/sources.list.d

Michael Walker
