### ISSUE TITLE
I can't connect using the ubuntu client

### ISSUE THREAD

**Issue by johnleebkk** [pritunl/pritunl#180]
TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
TLS Error: TLS handshake failed

Server: https://159.203.71.101:9700/#/servers (default uer/pass)

What can I do?

**Comment by johnleebkk** [comment]
Not even a reply? That's very nice of you. I wanted to see if pritunl is ok before buying a licence and possible hiring pritunl for commercial support and development......

**Comment by k0tkin** [comment]
Honey, when you are interested to a project made by a CHILD you don't deserve more ;)
