### ISSUE TITLE
Centos7 core - firewall problem

### ISSUE THREAD

**Issue by parsicode** [pritunl/pritunl#181]
hello, i install pritunl, every  things is ok, but i cant conect to server.
i add port  in firewall "firewall-cmd --zone=public --add-port=9700/tcp --permanent" now 9700 is open and ican create user, server,... in setting i set TCP port 8080, but pritunl cant conect to 8080,
i add "firewall-cmd --zone=public --add-port=8080/tcp --permanent" but port still close, selinux is disabled. http://ping.eu/port-chk/ show port 8080 is close. how to open it?

**Comment by changreich** [comment]
Maybe you can select iptables ;  systemctl stop firewall :)   (I cant understand how to conf ,but iptables is simple );
--- Attatch organization --> start the server (are you sure up the server ? )--> $ lsof -i :8080  what can you see ?
or change another port ?
I make it work in udp , not bad ...
