### ISSUE TITLE
Using debconf to automate web ui installation via CLI

### ISSUE THREAD

**Issue by josegonzalez** [pritunl/pritunl#183]
For automatically standing up a pritunl server with specific configuration, it would be useful to allow specifying all the web ui installation via `debconf` defaults. If those defaults were set, they would be imported automatically to the web ui, and if all were set, we could potentially skip the web ui entirely.

A generic alternative could be a cli tool that interfaces with a pritunl instance to setup the initial configuration of it.

/cc @evanccnyc in case he has more thoughts on the matter.

**Comment by zachhuff386** [comment]
Pritunl is built with [pacur](https://github.com/pacur/pacur) which builds to 5 different distros so any distro specific tools like `debconf` can't be used. The only significant option in `/etc/pritunl.conf` is the `mongodb_uri` which can be set using the command `pritunl set-mongodb MONGODB_URI`. An example of using this command to automate installs with cloud-init or similar systems is shown in the [AWS tutorial](https://medium.com/pritunl-tutorials/pritunl-advanced-tutorial-2be5cc57dff8)

**Comment by josegonzalez** [comment]
What about initial pritunl settings, such as username/password etc.? Would be useful to be able to automate that (setting up orgs and everything else can be done via the API once pritunl has it's initial configuration).

**Comment by zachhuff386** [comment]
It isn't very useful to automate those settings. Once one node in a cluster has been setup additional nodes that join the cluster will all have the same settings.

**Comment by josegonzalez** [comment]
Lets say I don't have a cluster setup and I want to automate that. I'm using a configuration management tool to stand up environments for users, and therefore would want to minimize the amount of browser interaction I do each time I create a standalone pritunl instance.

**Comment by zachhuff386** [comment]
There wouldn't be a lot of use cases for that. Other then the api there isn't going to be any new features added related to changing configuration options.

**Comment by josegonzalez** [comment]
Would you take a pull request that implemented such a feature?

**Comment by zachhuff386** [comment]
It would depend on how it was implemented. I don't really wan't several new command line options that replicate the functionality in the api.
