### ISSUE TITLE
Setting multiple DNS servers/Search domains

### ISSUE THREAD

**Issue by gtaylor** [pritunl/pritunl#186]
I couldn't find any direction on if this is supported or how I might do it. I'd like to be able to specify multiple search domains and DNS servers here:

![image](https://cloud.githubusercontent.com/assets/75556/10746842/e98c5f52-7c0b-11e5-9087-4f7b6a91803d.png)

Any suggestions?

**Comment by zachhuff386** [comment]
This can be done by separating the dns servers by a comma. Only one search domain can be used.
