### ISSUE TITLE
Cannot open config

### ISSUE THREAD

**Issue by brutser** [pritunl/pritunl#187]
I receive the following error when starting the server:

Options error: In [CMD-LINE]:1: Error opening configuration file: /tmp/pritunl_868cc7ae74f643d7b5b1836c202e66cd/fe595fef76f3459b9a9d7848c1363058/openvpn.conf
Wed Oct 28 16:34:23 2015 ERROR Management socket exception

**Comment by abkba** [comment]
This may be SELinux. Try `sudo setenforce 0`. Also, can you provide more specifics on what environment you have this setup on?

**Comment by brutser** [comment]
vps, centos 7.1

**Comment by brutser** [comment]
yes it is SELinux causing this, how can I configure SELinux to work with pritunl?

**Comment by zachhuff386** [comment]
SELinux isn't support, you will need to disabled it to use Pritunl
