### ISSUE TITLE
Ubuntu based client doesn't log.

### ISSUE THREAD

**Issue by InAnimaTe** [pritunl/pritunl#190]
Running `Pritunl Client - v1.0.738.83` on Linux Mint 17.2, I see:

```
┌[root@aquarius] 
└[/tmp]> ls -lah /var/log | grep pri
-rw-rw-r--  1 root              root      0 Sep 20 16:00 pritunl-client.log
-rw-rw-r--  1 root              root      0 Sep 20 16:00 pritunl-client.log.1
┌[root@aquarius] 
└[/tmp]> cat /var/log/pritunl-client.log
┌[root@aquarius] 
└[/tmp]> cat /var/log/pritunl-client.log.1
┌[root@aquarius] 
└[/tmp]> 

```

I'm actively connected and have made multiple logins in the past 24 hours.

**Comment by zachhuff386** [comment]
The logs are kept in the home directory at `~/.config/pritunl_client`

**Comment by InAnimaTe** [comment]
Ok then why do files exist in `/var/log`?

**Comment by zachhuff386** [comment]
The logs in `/var/log` are used for the errors in client the vpn logs are kept in `~/.config/pritunl_client`

**Comment by InAnimaTe** [comment]
Again, I have to mention that (I feel) this is poor design. Why would you write logs which contain two separate types of output to two completely different places?

I see this as a network service running on my system so consequently, logs (for both stdout/err) should probably exist only in `/var/log/pritunl_client`.

**Comment by zachhuff386** [comment]
The logs in `~/.config/pritunl_client` are relevant only to the vpn connection and user that created the log. It will contain potentially sensitive information that is relevant to the user and should not be accessible by other users on the system. The logs in `/var/log` are not specific to a vpn connection and shouldn't contain any sensitive information.
