### ISSUE TITLE
Ubuntu based client doesn't set DNS servers

### ISSUE THREAD

**Issue by InAnimaTe** [pritunl/pritunl#191]
Running `Pritunl Client - v1.0.738.83` on Linux Mint 17.2:

I have set the DNS server in the GUI for the specific Server I'm connecting to (an IPv4 address), however, that doesn't get applied in my `resolv.conf` at all...it doesn't change whatsoever when I connect. 

I have no logs as the Ubuntu based client doesn't log (see issue 190) so I have absolutely no clue what the client is even doing in the background. 

Any help for debugging this would be much appreciated.

**Comment by zachhuff386** [comment]
The dns servers usually need to be set manually with most network managers on linux.

**Comment by InAnimaTe** [comment]
Frankly, (I feel) this is poor design. You're building this fantastic application that's supposed to make it super easy to get a VPN working end-to-end but your not going to support, in your client, the ability to apply DNS settings, which is something *every* VPN client handles by default (the frontrunner for linux, OpenVPN, handles this just fine across distros)?

**Comment by zachhuff386** [comment]
The linux client is only a light gui wrapper around the `openvpn` application. It takes the configuration file and passes it as an argument to `openvpn`. Any issues with dns would likely be related to openvpn and the linux distro.

**Comment by InAnimaTe** [comment]
```
Mon Nov  9 17:12:06 2015 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014 
Mon Nov  9 17:12:06 2015 Control Channel Authentication: tls-auth using INLINE static key file 
Mon Nov  9 17:12:06 2015 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication 
Mon Nov  9 17:12:06 2015 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication 
Mon Nov  9 17:12:11 2015 UDPv4 link local: [undef] 
Mon Nov  9 17:12:11 2015 UDPv4 link remote: [AF_INET]50.25.43.2:1194 
Mon Nov  9 17:12:11 2015 VERIFY OK: depth=1, O=563ba55bc95c2e31c8a64fad, CN=563ba55cc95c2e31c8a64fb1 
Mon Nov  9 17:12:11 2015 Validating certificate key usage 
Mon Nov  9 17:12:11 2015 ++ Certificate has key usage  00a0, expects 00a0 
Mon Nov  9 17:12:11 2015 NOTE: --mute triggered... 
Mon Nov  9 17:12:12 2015 10 variation(s) on previous 3 message(s) suppressed by --mute 
Mon Nov  9 17:12:12 2015 [563ba55fc95c2e31c8a64fb6] Peer Connection Initiated with [AF_INET]52.2.172.153:1194 
Mon Nov  9 17:12:14 2015 Options error: Unrecognized option or missing parameter(s) in [PUSH-OPTIONS]:8: ip-win32 (2.3.2) 
Mon Nov  9 17:12:14 2015 TUN/TAP device tun0 opened 
Mon Nov  9 17:12:14 2015 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0 
Mon Nov  9 17:12:14 2015 /sbin/ip link set dev tun0 up mtu 1500 
Mon Nov  9 17:12:14 2015 /sbin/ip addr add dev tun0 10.255.0.7/16 broadcast 10.255.255.255 
Mon Nov  9 17:12:14 2015 Initialization Sequence Completed 
```

I'm guessing the `ip-win32` push option has something to do with this. For some reason, and it doesn't show in these logs, but a route for one of the other networks (network link) gets applied just fine.

I was going to try importing the ovpn but Network Manager just derps with an `unknown error`. Going to try to manually setup openvpn client.

**Comment by seglberg** [comment]
I guess I am running into some similar issues as @InAnimaTe heh. Anyways, this issues is preventing me from deploying this live at one of my client's sites. 

Without doing any debugging myself on the pritunl server, my Linux clients are not receiving the DNS option from the pritunl client as they do from my current OpenVPN server using the `push "dhcp-option DNS X.X.X.X"` option. I will see if Windows is working when I get a chance.

Thanks.
