### ISSUE TITLE
Ubiquiti client application doesn't work with 2FA enabled

### ISSUE THREAD

**Issue by InAnimaTe** [pritunl/pritunl#192]
I see a (on the recent log entries) `User failed two-step authentication "Home-Router".` and since there's no text box or option for entering a auth key on my device, it just sits there trying to auth. 

I'd like to suggest the possibility of allowing 2FA to be required on a per-user and/or per-organization basis.

**Comment by zachhuff386** [comment]
This will be fixed soon with more options to configure secondary authentication and ignoring secondary authentication for users with network links.

**Comment by zachhuff386** [comment]
Fixed in 1.9
