### ISSUE TITLE
Allow access to "Network Links" from users without necessity of "Inter-Client Communication" enabled

### ISSUE THREAD

**Issue by InAnimaTe** [pritunl/pritunl#193]
If I'm sharing a network from a user/gw I have connected of `10.50.0.0/24` and the Network of the VPN server (the client IP range) is `10.255.0.0./16`, those clients should be able to access the resources on the `10.50.0.0/24` network without "Inter-Client Communication" enabled. I view Inter-Client Communication only applying to that `10.255.0.0./16` network only, not a slew of resources shared from another subnet.

Ideally, it may be a good idea to provide a tickbox for the "Network Link" configuration to enable/disable access to it from certain organizations or users i.e. Administrators can access it but Engineering can't.

**Comment by zachhuff386** [comment]
It would still be consider inter-client communication because the network link is from a client. It could be confusing when the desired configuration is to only allow the server to access the network link so this likely won't change.

**Comment by seglberg** [comment]
Just wanted to point out that I was "bitten" by this issue recently. I had disabled inter-client communication but assumed the remote network would still be accessible as described by @InAnimaTe.
