### ISSUE TITLE
Utilize the "Public Address" setting for profile links

### ISSUE THREAD

**Issue by InAnimaTe** [pritunl/pritunl#194]
Profile links seem hit or miss when I go to view them. I've seen them show up with the reverse dns name of the server, the IP address of the server (when I'm using it to connect to GUI), and the actual Public Address I have set in the settings. This issue asks that you always serve them using the latter method (using the Public Address). Another possibility is to provide another box for the user to specify what domain what they want used in profile links.

**Comment by InAnimaTe** [comment]
One more thing: my organization is starting to use this excellent product in production (albeit for a small number of employees) and thus the wealth of bugs I've been filing (and future ones) will come out of our daily usage of the Premium version :) We really hope to help mold this offering into the best OpenVPN based VPN solution (and most cost effective for startups!)

**Comment by zachhuff386** [comment]
Are you referring to network links for users?

**Comment by zachhuff386** [comment]
The temporary profile links use the address that you accessed the web console with. If you go to https://vpn.domain.com:9700/ to access the web console then `vpn.domain.com` will be used for the profile links.

**Comment by InAnimaTe** [comment]
Why should the domain/IP an administrator accesses the webui with be the dependent factor in the domain/IP used to email a new employee his profile link? That just doesn't make sense to me. Why are you even bother taking in how they access the webui? That shouldn't matter for literally anything (that I can think of)..

Let me stress that I'm not trying to raise hell here or anything like that. Ideally, I'd like to see input from other users who are deploying this in production on all of these issues and help make a better decision about the direction of this great product :)

**Comment by zachhuff386** [comment]
It is difficult for the Pritunl server to accurately determine what dns/ip address should be used for clients accessing profile links. Adding a configuration option would complicate the settings and the url that was used to access the web console is generally the best way for clients to access the server.

**Comment by InAnimaTe** [comment]
>"It is difficult for the Pritunl server to accurately determine what dns/ip address should be used for clients accessing profile links."

Should be whatever the Administrator wants. That is, most likely, the "Public Address". Again, I'd like to get some other input from other people on this. I just feel like this should be configurable.
