### ISSUE TITLE
Not possible to connect to Windows PC's using Hostname/name

### ISSUE THREAD

**Issue by sanders54** [pritunl/pritunl#197]
Not sure if this is a Pritunl issue or OpenVPN, but I'm not able to for example RDP into computers using the hostname eg. "Sanders-PC" but I can connect using the IP (e.g 192.168.0.201). I'm connected to the local network with only local traffic mode. 

Maybe this is related to NetBIOS or whatever. Is it possible to forward this traffic too?

**Comment by bporter2387** [comment]
I had the same problem on Mac. Turns out I had to clear any previously set DNS names. Check the pritunl client log file for the error. It may be a related issue on Windows

**Comment by sanders54** [comment]
I don't have any errors in the log.

What did notice is that the network adapter is set to "public" which means it doesn't do the discovery process of finding other computers. I can't change it to "home" either.  I think this might be why it doesn't work, but it seems to be an OpenVPN issue rather than Pritunl. Any solution would be neat, though.

**Comment by seglberg** [comment]
So the root of this issue appears to be that DNS is not properly being set with Pritunl. (See #191 for similar issue). It works fine with OpenVPN, so it appears to be a problem with Pritunl. 

I have tested that DNS does not get set on both Linux (Arch, no dnsmasq was not running) and Windows (Windows 7 and Windows 10). 

Unfortunately this is holding up 2 deployments that I would like to move over to Pritunl, as it is not acceptable to have my Windows users set their DNS manually when they enable the VPN.

**Comment by seglberg** [comment]
Just to clarify, we currently use OpenVPN with the `push "dhcp-option DNS X.X.X.X"` option and it works perfect on both Linux and Windows.

**Comment by zachhuff386** [comment]
Not able to reproduce this issue
