### ISSUE TITLE
Multiple Admin Users.

### ISSUE THREAD

**Issue by agottschling** [pritunl/pritunl#201]
This doesn't have to get done asap, but maybe for the next major release. I'd like the ability to have multiple admin users that can access the webui. Even if they have the same permissions as the first user.

**Comment by abkba** [comment]
+1 for this.

**Comment by seanthewebber** [comment]
Also a +1 for me. Only having one administrative user for installations managed by teams is a pain.

**Comment by zachhuff386** [comment]
This was added in 1.14
