### ISSUE TITLE
CentOS 7 bag 

### ISSUE THREAD

**Issue by VirKing** [pritunl/pritunl#203]
Recent log entries
Stopped server "v". 4:26 am - Nov 23 2015
Server stopped unexpectedly "v". 4:26 am - Nov 23 2015
Server stopped unexpectedly "v". 4:25 am - Nov 23 2015
Server stopped unexpectedly "v". 4:25 am - Nov 23 2015
Started server "v". 4:25 am - Nov 23 2015
Created server "v". 4:23 am - Nov 23 2015

[summer-forest-4122] Options error: In [CMD-LINE]:1: Error opening configuration file: /tmp/pritunl_3007817e21324acfadcd0dec947e9b11/14be2607d0a94120b51ebddfed606bd4/openvpn.conf
[summer-forest-4122] Use --help for more information.
[summer-forest-4122] Options error: In [CMD-LINE]:1: Error opening configuration file: /tmp/pritunl_3007817e21324acfadcd0dec947e9b11/808e9da8460f4180870f82947a589ed2/openvpn.conf
[summer-forest-4122] Use --help for more information.
[summer-forest-4122] Mon Nov 23 02:26:54 2015 ERROR Management socket exception
[summer-forest-4122] Mon Nov 23 02:27:30 2015 ERROR Management socket exception
[summer-forest-4122] Mon Nov 23 02:27:44 2015 ERROR Management socket exception

**Comment by VirKing** [comment]
[root@~]# openvpn --config
Options error: Unrecognized option or missing parameter(s) in [CMD-LINE]:1: config (2.3.8)
Use --help for more information.

**Comment by zachhuff386** [comment]
This is likely an issue with SELinux
