### ISSUE TITLE
Add ability to manually define routes to push

### ISSUE THREAD

**Issue by InAnimaTe** [pritunl/pritunl#206]
In some cases, an administrator might need to manually define routes. An example of this could be the need to provide access to VPN clients to a private network the VPN server is connected to (via other interfaces)

I envision this should be available on the Server configuration window with a simple box where you provide the network to push a route for.

**Comment by zachhuff386** [comment]
The network routes can be defined by setting the server mode to Local Traffic Only and adding the networks to the Local Networks input.

**Comment by InAnimaTe** [comment]
Ahh looking at https://github.com/pritunl/pritunl/wiki/Server seems to clear that up. Maybe rename it to be a bit clearer (that it still supports client-to-client traffic)
