### ISSUE TITLE
Create an official docker image

### ISSUE THREAD

**Issue by eterry1388** [pritunl/pritunl#208]
I would love to see official support for running Pritunl within a Docker container.  I have used this one:  https://hub.docker.com/r/johnae/pritunl , but I don't know how well it would work in an enterprise setup and it doesn't seem to be updated regularly.

**Comment by zachhuff386** [comment]
There isn't any logical reason to run Pritunl in a Docker container, it's very similar to a router which wouldn't be put in a Docker container. The pritunl-link software will have a Docker image available when released.

**Comment by eterry1388** [comment]
I am running everything in docker images these days and using https://www.tutum.co/ for my hosting.  Docker is replacing the concept of virtual machines.  Being able to tie it into my existing environments would really be nice (like linking my mongodb docker containers to pritunl without having to expose mongodb ports).

**Comment by jonathanpa** [comment]
@eterry1388 The pritunl docker image done by johnae is not updated regularly. I made a pull-request to him but I didn't get updates from my PR. You can have a look on my fork [jonathanpa/pritunl](https://github.com/jonathanpa/pritunl) and on my [pull-request](https://github.com/johnae/pritunl/pull/1).

**Comment by johnae** [comment]
Sorry I missed that pull request. My image was more or less thrown together to get a connection going from work to home. Pritunl makes it much easier than managing openvpn manually.

Wrt to an enterprise setup I don't know what one would want but to me there are good reasons for using a Docker image for pritunl.

**Comment by sstarcher** [comment]
I second the request for an official image

**Comment by h0tbird** [comment]
> There isn't any logical reason to run Pritunl in a Docker container

I bet all CoreOS users are in disagreement.

**Comment by sstarcher** [comment]
@h0tbird +1

**Comment by eterry1388** [comment]
@h0tbird :+1:

**Comment by bogar** [comment]
@h0tbird :+1:

**Comment by sstarcher** [comment]
@h0tbird your alpine container looks good https://github.com/h0tbird/docker-pritunl
