### ISSUE TITLE
API for a user doesn't show "servers" key

### ISSUE THREAD

**Issue by eterry1388** [pritunl/pritunl#211]
When I call the API (GET /user/:org_id) to view all users, I see the `servers` key on each user in the array . However, when I call the API (GET /user/:org_id/:user_id) to get an individual user, the `servers` key is missing.  According to documentation, it is supposed to be there.  This is what I get:

```
{
auth_type: "local",
dns_servers: null,
otp_secret: "-----------------",
dns_suffix: null,
disabled: false,
bypass_secondary: false,
id: "-------------------------",
name: "-------------------",
organization_name: "--------------",
organization: "--------------",
type: "client",
email: "----------------"
}
```

**Comment by y3tiy3ti** [comment]
I have the same issue, i can create a user and that comes back just fine. As soon as i go to get the users key, i get a 401 

Unauthorized


The server could not verify that you are authorized to access the URL requested.  You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.

**Comment by zachhuff386** [comment]
The individual user handler does return less information then the list users handler. The individual user handler isn't used by the web console so it hasn't been fully completed to provide all the information that the list handler does.

I wasn't able to reproduce the 401 api error the following code will download a user profile with the api

```python
import requests, time, uuid, hmac, hashlib, base64
BASE_URL = 'https://127.0.0.1:9700'
API_TOKEN = 'token'
API_SECRET = 'secret'

def auth_request(method, path, headers=None, data=None):
    auth_timestamp = str(int(time.time()))
    auth_nonce = uuid.uuid4().hex
    auth_string = '&'.join([API_TOKEN, auth_timestamp, auth_nonce,
        method.upper(), path] + ([data] if data else []))
    auth_signature = base64.b64encode(hmac.new(
        API_SECRET, auth_string, hashlib.sha256).digest())
    auth_headers = {
        'Auth-Token': API_TOKEN,
        'Auth-Timestamp': auth_timestamp,
        'Auth-Nonce': auth_nonce,
        'Auth-Signature': auth_signature,
    }
    if headers:
        auth_headers.update(headers)
    return getattr(requests, method.lower())(
        BASE_URL + path,
        verify=False,
        headers=auth_headers,
        data=data,
    )

response = auth_request('GET',
  '/key/org_id/user_id.tar',
)
assert(response.status_code == 200)
print response.content
```

**Comment by eterry1388** [comment]
@zachhuff386 Why is this closed?  Your documentation is inaccurate to what the API is actually doing.  I think this needs to be reopened to either make the documentation accurate to write the API to conform to the API.
