### ISSUE TITLE
Some Feature Requests

### ISSUE THREAD

**Issue by benmaynard11** [pritunl/pritunl#215]
1. Have the ability to send all internet traffic AND select/all local subnets on the same VPN server. The current settings do not allow you to do this. You must either specify all internet traffic and no local subnets, or local subnets and no internet traffic. This might be achievable through linking servers on Enterprise, but I think this should be available on Premium.

2. Make the custom SSL option available to Premium users. SSL should not come at a premium. Nobody realistically checks the fingerprints of the SSL certificate every time they visit the administration panel, and so it would be great if we could use a custom certificate signed by a trusted Root CA. Even better idea? Why not implen. Those paying for Premium should be able to add a custom SSL certificate.

4. Support for iOS .mobileconfig file generation, including VPN on demand. This would be really easy to implement, in fact, OpenVPN Access Server already have a script to do this. You could just copy it and run the .ovpn files through it. It'd do the rest.

4. Supporting the signing of the client certificates through a custom certificate authority. 

5. IPv6 currently does not work for the All Traffic option if you have UFW enabled, but IPv4 does. Can Pritunl modify the default UFW settings to allow IPv6 Internet Traffic without manual modification?

**Comment by eterry1388** [comment]
:+1: for number 3.  We'd love to see the ability to lock down the .mobileconfig with a passcode as well so it cannot be removed without it.

**Comment by brnmckllr** [comment]
I agree on #3. The 'Apple Configurator 2' used to create .mobileconfig has been extremely confusing when using pritunl and OpenVPN. Can't figure out how to get all traffic forced through the VPN.

**Comment by eterry1388** [comment]
Are mobileconfig files now supported?

**Comment by zachhuff386** [comment]
Support for mobileconfig isn't going to be added

**Comment by eterry1388** [comment]
Okay thanks.  What of the 5 features above did you add?

**Comment by zachhuff386** [comment]
None of the features above are going to be added
