### ISSUE TITLE
Dial Home Activation

### ISSUE THREAD

**Issue by benmaynard11** [pritunl/pritunl#216]
I think it is terrible that if Pritunl cannot dial home, then it reverts back to the free version. If the https://app.pritunl.com service goes down, then every single customer will temporarily use the additional feature set provided by their Premium / Enterprise subscription.

**Comment by zachhuff386** [comment]
There isn't any plans to change the subscription system

**Comment by benmaynard11** [comment]
Zach,

I understand why you might be reluctant to change this, but surely you can see the huge flaw in the current design? How can Pritunl be sold to Enterprise customers in good faith, when you know that the second the https://app.pritunl.com service goes offline, every single customer will instantly lose the added functionality purchased through their subscription?

I have absolutely no issues with Pritunl dialling home for activation, but the current way that the system is designed is hugely flawed. You have no way of ensuring 100% uptime of the https://app.pritunl.com. service, and to **not even offer a grace period** where the server will remain activated if it cannot communicate with the activation server is poor design.

I mean, it's not like AWS ever has outages, [am I right?](http://www.theregister.co.uk/2015/09/20/aws_database_outage/) or [am I right?](http://www.theregister.co.uk/2015/09/28/whoops_there_goes_my_cloud/) or [am I right?](http://www.crn.com/news/cloud/300077740/overnight-aws-outage-reminds-world-how-important-aws-stability-really-is.htm)

If you won't at least offer a grace period, you should probably update the text on the Pritunl homepage to read "As long as there isn't an AWS Outage, Virtualize your private networks across datacenters and provide simple remote access in minutes."
