### ISSUE TITLE
Turn off logging

### ISSUE THREAD

**Issue by e-oz** [pritunl/pritunl#217]
Hello.
Please help me find how to turn off logs completely. I don't need logs and graphs, but with time db just takes whole disk space because of logs. I only want to know if my VPN work or not, and I can find it without logs. So if there any setting/workaround/hack - please let me know.

**Comment by e-oz** [comment]
And thank you for this software - I like it very much :)

**Comment by zachhuff386** [comment]
The vpn server logs have a limit of 5000 lines and the graphs are limited to what is show in each time period. Older entries will be removed when the limit is reached so disk usage shouldn't be an issue. The server logs can be disabled by running the command `pritunl set vpn.log_lines 0` the graphs cannot be disabled. The system logs have a limit of 10000 this can be changed with `pritunl set app.log_limit 0`

**Comment by e-oz** [comment]
It's third time I reinstall it because of empty disk space (only thing exist on this server is pritunl). Maybe issue is in limit of graphs - 365 days it's big enough period.
Anyway, thanks for help.

**Comment by InSolemmenT** [comment]
How can i put on pritunl 30 days limit certificate key expire like on openvpn?
