### ISSUE TITLE
Trouble authenticating to the API

### ISSUE THREAD

**Issue by thepaleone** [pritunl/pritunl#218]
I'm trying to write a client in c# to integrate into a control portal; however I"m having a hard time authenticating to the API. The "/ping" request is the only one that seems to work, all others return a 401 Unauthorized.

I've tested my hashing function and, given the same values, it will produce the same output as the sample python script from the documentation page. Here's what I'm doing:

```c#
private WebClient GetWebClient(string method, string path)
{
    string timeStamp = DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1)).TotalSeconds.ToString();
    string nonce = Guid.NewGuid().ToString("n");
    string hash = GetHashedSignature(timeStamp, nonce, method, path);

    WebClient client = new WebClient();
    client.Headers.Add("Auth-Token", _apiToken);
    client.Headers.Add("Auth-Timestamp", timeStamp);
    client.Headers.Add("Auth-Nonce", nonce);
    client.Headers.Add("Auth-Signature", hash);
    ServicePointManager.ServerCertificateValidationCallback = (a, b, c, d) => true;

    return client;
}

 private string GetHashedSignature(string timeStamp, string nonce, string method, string path)
 {
     string signature = string.Join("&", _apiToken, timeStamp, nonce, method.ToUpper(), path);

     Encoding encoding = new ASCIIEncoding();
     byte[] key = encoding.GetBytes(_apiSecret);
     byte[] message = encoding.GetBytes(signature);

     using (HMACSHA256 hmac = new HMACSHA256(key))
     {
         byte[] hash = hmac.ComputeHash(message);
         return Convert.ToBase64String(hash);
     }
 }
```

I'm calling using those functions like this
```c#
path = "/organization";
using (WebClient client = GetWebClient("GET", path))
{
    Uri address = GetUrl(path, args);
    string result = client.DownloadString(address);
    return result;
}
```

That code results in a 410. If I change path to "/ping" it works just fine. Any suggestions would be appreciated.

Thanks in advance
-Joel

**Comment by dverbeek84** [comment]
Joel, I have the same problem :cry:

**Comment by dverbeek84** [comment]
I have just checked the different versions, but the API broken in v1.14.842.79. In version v1.13.836.1 is is just working fine. Something to do with `Add multiple administrators`?

**Comment by zachhuff386** [comment]
When adding multiple administrators, multiple api keys were also added. The api authentication can also be enable/disabled per admin. This included refactoring the current api authentication. It's possible in a future release api authentication will be added back into non-enterprise but for now api authentication can only be done with an enterprise subscription.
