### ISSUE TITLE
Connections doesn't appear in interface

### ISSUE THREAD

**Issue by Wouter0100** [pritunl/pritunl#220]
First, thanks for this awesome software! I've set this up in some seconds, and mostly it worked perfect. The only downside is that connections (and online people) doesn't appear in the web interface. Nobody is never online and no devices are connected.

After looking in my logs, I see [this](https://gist.github.com/Wouter0100/2c320c1d61e5f8d6a054). This appears when a user connects to the VPN through the Pritunl client. 

I'm running Ubuntu 14.04.3 LTS on a VPS. I've a single external IP and 2 VPN's on internal networks. I just installed the Pritunl, added the organisations, users and then added the servers. After that these errors appeared when a user connects.

**Comment by zachhuff386** [comment]
This will be fixed in v1.15.857.70
