### ISSUE TITLE
Let's Encrypt intergration

### ISSUE THREAD

**Issue by Wouter0100** [pritunl/pritunl#221]
It would be awesome if the SSL certificate of the webinterface could be automatically signed and configured by Pritunl. This could be done through the free Let's Encrypt project.

**Comment by zachhuff386** [comment]
I have done some testing with it but it won't be added until the Let's Encrypt Beta is finished.

**Comment by Wouter0100** [comment]
Okay! Nice you did already some tests :)

**Comment by adamgoose** [comment]
Any update on this? I see the field in Settings (fresh install), however it continues to fail.

```[lively-dreams-2549][2016-03-25 14:09:07,811][INFO] Parsing acme account key...
[lively-dreams-2549][2016-03-25 14:09:07,821][INFO] Parsing acme CSR...
[lively-dreams-2549][2016-03-25 14:09:07,844][INFO] Registering acme account...
[lively-dreams-2549][2016-03-25 14:09:08,605][INFO] Registered acme certificate
[lively-dreams-2549][2016-03-25 14:09:08,606][INFO] Verifying acme domain my-domain...
[lively-dreams-2549][2016-03-25 14:09:09,395][ERROR] Failed to get LetsEncrypt cert
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/settings.py", line 528, in settings_put
    acme.update_acme_cert()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/acme.py", line 49, in update_acme_cert
    cert = get_acme_cert(settings.app.acme_key, csr)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/acme.py", line 24, in get_acme_cert
    app.set_acme,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/acme_tiny.py", line 139, in get_crt
    raise ValueError("Couldn't download {0}".format(wellknown_url))
ValueError: Couldn't download http://my-domain/.well-known/acme-challenge/fFoPL2rX6PwoUabUinwVi1BfVevm3lgM1dd0x2XgqXQ
  acme_domain = u'my-domain'```

**Comment by sankros** [comment]
Great idea. Received the certificate for the pritunl server in 1 click. but there is a problem with mobile browsers. if I view site on android or ios device there is an security error. How to fix it?

**Comment by zachhuff386** [comment]
The issue with mobile browsers was due to the intermediate certificates missing. This will be fixed in the next release.

**Comment by k0nsl** [comment]
I am having the same issue as @adamgoose. I am running Pritunl 1.21.967.90 a8b3c4 (stable branch).
I can successfully reach a test file at `http://subdomain.mydomain.tld/.well-known/acme-challenge/test.txt`.
However, Pritunl throws this error:
```
[winter-waters-7988][2016-05-07 14:07:10,519][INFO] Parsing acme account key...
[winter-waters-7988][2016-05-07 14:07:10,544][INFO] Parsing acme CSR...
[winter-waters-7988][2016-05-07 14:07:10,564][INFO] Registering acme account...
[winter-waters-7988][2016-05-07 14:07:11,690][INFO] Registered acme certificate
[winter-waters-7988][2016-05-07 14:07:11,691][INFO] Verifying acme domain vpn.k0nsl.ru...
[winter-waters-7988][2016-05-07 14:07:12,402][ERROR] Failed to get LetsEncrypt cert
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/settings.py", line 541, in settings_put
    acme.update_acme_cert()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/acme.py", line 49, in update_acme_cert
    cert = get_acme_cert(settings.app.acme_key, csr)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/acme.py", line 24, in get_acme_cert
    app.set_acme,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/acme_tiny.py", line 139, in get_crt
    raise ValueError("Couldn't download {0}".format(wellknown_url))
ValueError: Couldn't download http://subdomain.mydomain.tld/.well-known/acme-challenge/XrnVdrpjy2MxbqdP-09Y9NIq75nULmxfFINHstC9cjM
  acme_domain = u'subdomain.mydomain.tld'
``` 
Thanks in advance for any help.

**Comment by zachhuff386** [comment]
Port 80 must be open and publicly accessible. The DNS record must also point to the Pritunl server.

**Comment by k0nsl** [comment]
@zachhuff386: yes, I know, which is why I previously wrote:

>I can successfully reach a test file at http://subdomain.mydomain.tld/.well-known/acme-challenge/test.txt.

Hence, port 80 is open and publicly accessible. The corresponding DNS record is naturally added, as well.
Still, the issue persists.

**Comment by zachhuff386** [comment]
Pritunl won't serve a test file if you are not getting a 404 at `/.well-known/acme-challenge/test.txt` a different server is most likely running on port 80.

**Comment by k0nsl** [comment]
@zachhuff386: Yes, you're correct. I incorrectly assumed that I needed nginx for this to work.
At any rate, I stopped nginx and made sure it was actually stopped — still no luck!
Do I need to create the `.well-known` directory somewhere on my server, or is this handled automatically or through some other way?

Thanks for your help.

**Comment by zachhuff386** [comment]
The Pritunl server will handle the acme-challenge there shouldn't be anything running on port 80.

**Comment by k0nsl** [comment]
Roger that. Well, nothing is running on port 80 now and it still won't issue the certificate; the error raised is precisely the same as it was before.
