### ISSUE TITLE
Upload Speed

### ISSUE THREAD

**Issue by frederichoule** [pritunl/pritunl#222]
I was running OpenVPN Access Server for approximatively the last 5-6 months. I have a 50mbps/50mbps link at home, and when I was on my VPN I had 50/50 speed on any speedtest online.

Now I switched for Pritunl yesterday. I love it. Except that I get 50/~6 speed, instead of 50/50.

Is there anything I can change in the configuration somewhere to fix that?

By the way, my VPN is hosted on a multi-gigabit private dedicated cloud, and I can easily attain 1gbps speed if my home connection would handle it.

Thanks!

**Comment by zachhuff386** [comment]
Try setting `DH Param Bits` to `1024` and `Hash Algorithm` to `SHA-1` in the advanced server settings. It is also possible QoS is limiting the speed, use the same port and protocol when testing.
