### ISSUE TITLE
Pritunl Won't Start Centos 7

### ISSUE THREAD

**Issue by soehlert** [pritunl/pritunl#225]
Here is some relevant info. It says it's running according to status, however, it does not respond on port 9700. Nothing is listening. It looks like the webserver process fails due to a problem creating a cert (maybe)?

[root@vpn log]# cat /etc/redhat-release
CentOS Linux release 7.1.1503 (Core)

[root@vpn log]# netstat -tulpn | grep 9700
[root@vpn log]#

[root@vpn log]# ps -ef | grep pritunl
root      2272     1  0 19:21 ?        00:00:00 /usr/lib/pritunl/bin/python2 /usr/lib/pritunl/bin/pritunl start --daemon --pidfile /var/run/pritunl.pid

[root@vpn log]# systemctl status pritunl
● pritunl.service - Pritunl Daemon
   Loaded: loaded (/etc/systemd/system/pritunl.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2016-01-18 19:21:15 UTC; 3min 21s ago
  Process: 2260 ExecStart=/usr/lib/pritunl/bin/pritunl start --daemon --pidfile /var/run/pritunl.pid (code=exited, status=0/SUCCESS)
 Main PID: 2272 (pritunl)
   CGroup: /lxc/102/system.slice/pritunl.service

[root@vpn log]# cat /var/log/messages | grep pritunl
Jan 18 19:20:45 vpn yum[1257]: Installed: pritunl-1.15.857.70-1.el7.centos.x86_64
Jan 18 19:21:01 vpn systemd: Configuration file /etc/systemd/system/pritunl.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Jan 18 19:21:01 vpn systemd: Configuration file /etc/systemd/system/pritunl.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Jan 18 19:21:07 vpn systemd: Configuration file /etc/systemd/system/pritunl.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Jan 18 19:21:07 vpn systemd: Configuration file /etc/systemd/system/pritunl.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Jan 18 19:21:07 vpn systemd: Configuration file /etc/systemd/system/pritunl.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Jan 18 19:21:07 vpn systemd: Configuration file /etc/systemd/system/pritunl.service is marked executable. Please remove executable permission bits. Proceeding anyway.
Jan 18 19:21:15 vpn pritunl: Exception in thread Thread-2:
Jan 18 19:21:15 vpn pritunl: Traceback (most recent call last):
Jan 18 19:21:15 vpn pritunl: File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
Jan 18 19:21:15 vpn pritunl: self.run()
Jan 18 19:21:15 vpn pritunl: File "/usr/lib64/python2.7/threading.py", line 764, in run
Jan 18 19:21:15 vpn pritunl: self.__target(*self.__args, **self.__kwargs)
Jan 18 19:21:15 vpn pritunl: File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/setup/server.py", line 154, in server_thread
Jan 18 19:21:15 vpn pritunl: utils.generate_server_cert(server_cert_path, server_key_path)
Jan 18 19:21:15 vpn pritunl: File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/utils/cert.py", line 11, in generate_server_cert
Jan 18 19:21:15 vpn pritunl: '-out', server_cert_path,
Jan 18 19:21:15 vpn pritunl: File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/utils/misc.py", line 160, in check_output_logged
Jan 18 19:21:15 vpn pritunl: *args, **kwargs)
Jan 18 19:21:15 vpn pritunl: File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
Jan 18 19:21:15 vpn pritunl: errread, errwrite)
Jan 18 19:21:15 vpn pritunl: File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
Jan 18 19:21:15 vpn pritunl: raise child_exception
Jan 18 19:21:15 vpn pritunl: OSError: [Errno 2] No such file or directory

**Comment by zachhuff386** [comment]
Check that openssl is installed. Could also be an SELinux issue.

**Comment by soehlert** [comment]
That was it. Thank you for the super prompt response!
