### ISSUE TITLE
View pritunl server logs on command line

### ISSUE THREAD

**Issue by eterry1388** [pritunl/pritunl#226]
According to [this wiki article](https://github.com/pritunl/pritunl/wiki/Logs-and-Debugging) you can run `pritunl logs --tail` to view and tail system logs.  I want to be able to tail a vpn server's logs (the ones under "server" and "server output" in the GUI that shows when users have connected and disconnected).  Is there a way to view these on the command line?  I  know I can see them by using the api `GET /server/:server_id/output`, but I want to be able to tail the logs.

**Comment by zachhuff386** [comment]
There isn't any command to view the vpn server logs.
