### ISSUE TITLE
API keys

### ISSUE THREAD

**Issue by hilbertknl** [pritunl/pritunl#227]
Hello,

I want to work with the API but where can I find the keys?
It's not under the settings taband Google doesn't say much.
I'm using the free version on CentOS 7 64x

**Comment by eterry1388** [comment]
See this issue for more detail:  Trouble authenticating to the API #218 .

**Comment by hilbertknl** [comment]
That's not the question.
Where in the web interface can I find my API keys?

**Comment by eterry1388** [comment]
Yes it is.  Read the last comment on that issue.  It states:  "It's possible in a future release api authentication will be added back into non-enterprise but for now api authentication can only be done with an enterprise subscription."

You cannot use the API on the free version.
