### ISSUE TITLE
Feature request: Management for large numbers of orgs

### ISSUE THREAD

**Issue by scriby** [pritunl/pritunl#235]
I have 100 organizations setup in pritunl. If I'm looking for a particular user, I have to go through 20 pages to find them.

It would be helpful if I could search for users across all organizations for a particular user.

Thanks,

Chris

**Comment by zachhuff386** [comment]
Most use cases don't involve more then a few organizations so there won't be any changes to the search system.

**Comment by scriby** [comment]
Thanks for the feedback. This is something I'll have to handle one way or another.

Is this something you'd consider a pull request for? I could also fork, or implement it in another app by hitting the DB directly (I'm pretty sure I can't implement it efficiently against the API).

Thanks,

Chris
