### ISSUE TITLE
Server cannot start if it has more than 5 organizations attached

### ISSUE THREAD

**Issue by scriby** [pritunl/pritunl#236]
I added 50 orgs to a server, and it failed to startup with the following error:

```
[vpn-1] Fri Jan 29 00:07:17 2016 ERROR Management socket exception
[vpn-1] Fri Jan 29 00:07:17 2016 OpenVPN 2.3.6 x86_64-redhat-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Dec 10 2014
[vpn-1] Fri Jan 29 00:07:17 2016 library versions: OpenSSL 1.0.1k-fips 8 Jan 2015, LZO 2.08
[vpn-1] Fri Jan 29 00:07:17 2016 Cannot load CA certificate file [[INLINE]] (no entries were read): error:0906D066:PEM routines:PEM_read_bio:bad end line
[vpn-1] Fri Jan 29 00:07:17 2016 Exiting due to fatal error
```

I removed servers until it would start, and noticed that it won't start if there are any more than 5 orgs attached. Can this limit be increased?

Thanks,

Chris

**Comment by zachhuff386** [comment]
What distro and version are you using?

**Comment by scriby** [comment]
I am running the Pritunl AMI provided by you. Just re-provisioned new servers with it today.

I don't know if the AMI installs the latest version of the software. I didn't see a way to get the version from the UI.

**Comment by scriby** [comment]
Did I get you enough information to answer your question? If not, could you give me a command or something to run to look up the version?

**Comment by zachhuff386** [comment]
This appears to be an issue with specific versions of openvpn

**Comment by scriby** [comment]
How should I proceed?

**Comment by scriby** [comment]
I got openvpn 2.3.10 installed from source and it fixed the problem. Thanks for the help.
