### ISSUE TITLE
Feature request: Administrator approval for Single Sign-On accounts

### ISSUE THREAD

**Issue by tobijb** [pritunl/pritunl#237]
Hi there,

We're using the Google Apps domain and it would be super sweet to tie users to a Google Apps organization for limiting who has access to the Single Sign-On functionality.  

Another option is maybe having an approval gate with an email to the admin to approve accounts before they can login for the first time.  This would limit the issue of "any user in the domain can get on the VPN using Single Sign-On with Google Apps."  

Thanks for such an amazing product!

**Comment by zachhuff386** [comment]
The Google API doesn't provide group or organization info.
