### ISSUE TITLE
Static IP adress for each user access my VPN?

### ISSUE THREAD

**Issue by FakerFd** [pritunl/pritunl#238]
Hello,

I have one Pritunl VPN server with private Local Networks:

172.30.24.0/24

And for users I use internal Network:

192.168.215.0/24

Тhere are 4 users and (4 machines with a set of static address from the private Local Networks 172.30.24.1, 172.30.24.2,...172.30.24.4).

I want to give each user access with specific IP address to the internal network (my VPN Server). And then this user with a static IP address,  to be able to connect only to a specific IP address in the private network.

**## Example:**

_User 1 (Need to give him 192.168.215.2 static) to access only machine 1 with IP address 172.30.24.2) in private Local Networks.
.....
User3 (Need to give him 192.168.215.3 static) to access only machine 3 with IP address 172.30.24.3) in private Local Networks._

How to give a static IP address to each user from the 192.168.215.0/24 and routing to each of them only to one adress from the private Local Networks.

Is it possible to help me... ?

**Comment by scriby** [comment]
Not sure if this will help, but I noticed in the POST user API (https://pritunl.com/api.html#post-user-var) you can pass a virt_address. Maybe if you use the API to set that value it will force the IP?
