### ISSUE TITLE
Question: Creating pritunl instance clones

### ISSUE THREAD

**Issue by scriby** [pritunl/pritunl#242]
Hi,

I setup pritunl on an AWS instance and created an AMI of it. Servers I launch using the AMI seem to connect to the DB as the same host as the original instance. How can I modify the image such that the new instance shows up as a new host in pritunl?

Thanks,

Chris

**Comment by zachhuff386** [comment]
The pritunl-nomongodb is available in the AWS community AMIs and the command `pritunl set-mongodb MONGODB_URI` is available to set the MongoDB server.

**Comment by scriby** [comment]
I'm not able to use the AMI because I need a later version of openvpn.

My issue is not with setting the mongo db URI. The issue is that the additional hosts that I create by cloning my own image do not show up in the UI. I assumed it was because each host had a unique ID or something, and because I was using a clone it causes two hosts to use the same ID.

**Comment by zachhuff386** [comment]
You need to clear the host id in `/var/lib/pritunl/pritunl.uuid`

**Comment by scriby** [comment]
Great, thanks!
