### ISSUE TITLE
Too many certificates included in open vpn profile

### ISSUE THREAD

**Issue by scriby** [pritunl/pritunl#248]
I recently tried to generate a profile for a user who is a member of a single organization. Openvpn errored when attempting to use the profile:

`Thu Feb 11 11:42:39 2016 Cannot load CA certificate file [[INLINE]]: error:0906D066:lib(9):func(109):reason(102)`

I opened the profile and noticed it contained 50 certificates (under the ca node in the xml). I suspect that this is related to the fact that I have 50 organizations attached to a single server. Would that cause more certificates to get included in the profile? If so, is that a bug?

**Comment by zachhuff386** [comment]
All organization CA certs are included in the profile

**Comment by scriby** [comment]
If a user can only be part of one organization, why are the certs for the other orgs necessary?
