### ISSUE TITLE
SSO for multiple Organisations

### ISSUE THREAD

**Issue by ITSAM-natgruppen** [pritunl/pritunl#252]
Hi!

We would like to get the ability to assign SSO to more than one Organisation within Pritunl, or the ability to assign different ip-ranges via Radius reply/attribute when a user login to the VPN.

**Comment by zachhuff386** [comment]
Check https://github.com/pritunl/pritunl/tree/master/pritunl/sso

**Comment by ITSAM-natgruppen** [comment]
If I would like to assign Radius-SSO to all the organisations attached 
to different servers(with different ip-ranges) on the same node, what do 
I have to do?
