### ISSUE TITLE
Possible ip space on wiki includes network that is in use

### ISSUE THREAD

**Issue by delgurth** [pritunl/pritunl#253]
On this wiki page: https://github.com/pritunl/pritunl/wiki/Server it's said that you can for example use the 50.203.0.0/16 network space, with the note (Reserved in public space). But for example the .16.61 address is already being used:

http://www.tcpiputils.com/browse/ip-address/50.203.16.61

I was going to say that you could perhaps use the ip space being used to do the star wars intro's via traceroute, but since that is (currently) not working, I wouldn't suggest using that one either.

**Comment by zachhuff386** [comment]
This range was purchased by a VPN company to use for private addresses to prevent address conflicts.

**Comment by delgurth** [comment]
@zachhuff386 I expected it to be something like that, but I couldn't find anything where the 50.203.0.0/16 network was being claimed to be free to use. The only thing I found where real websites residing in the ip space, see the link in my original issue. So claiming that whole 50.203.0.0/16 is free to use is incorrect, at least if you also want to be able to visit www.redbrand.com

**Comment by zachhuff386** [comment]
I believe the company is closing they must have sold the range, the wiki has been updated.
