### ISSUE TITLE
Queries are not indexed correctly - Server stopped unexpectedly

### ISSUE THREAD

**Issue by US9IDX** [pritunl/pritunl#254]
Hi-
As the database MongoDB I use the paid fare and powerful MongoLab (mongolab.com)

When I look at your queries they I can see that they are not indexed properly. As a result your queries will get slower as the data set grows.
You can read more generally about indexes here:
https://docs.mongodb.org/manual/core/indexes/
In particular this query:

`2016-02-14T14:10:31.721-0800 I COMMAND  [conn1328742] command pritunl.$cmd command: aggregate { aggregate: "servers", pipeline: [ { $match: { status: "online", start_timestamp: { $lt: new Date(1455487800433) } } }, { $project: { instances: true, _id: true, hosts: true, replica_count: true, offline_instances_count: { $subtract: [ "$replica_count", "$instances_count" ] } } }, { $match: { offline_instances_count: { $gt: 0 } } } ], cursor: {} } keyUpdates:0 writeConflicts:0 numYields:0 reslen:103 locks:{ Global: { acquireCount: { r: 6 } }, MMAPV1Journal: { acquireCount: { r: 3 }, acquireWaitCount: { r: 1 }, timeAcquiringMicros: { r: 1005598 } }, Database: { acquireCount: { r: 3 } }, Collection: { acquireCount: { R: 3 } } } 508ms`
**Could use this index:**
`{ "status": 1, "start_timestamp": 1}`

> Protocol: udp
> Network: 10.53.0.0/16
> DNS Server: 8.8.8.8
> Mode: All Traffic
> Allow Multiple Devices: Disabled
> Enable Two-Step Authentication: Disabled
> DH Param Bits: 1536
> Encryption Cipher: AES 256
> DNS Search Domain: Blank
> Ping Interval: 10
> Ping Timeout: 60
> Max Clients: 1024
> Inter-Client Communication: OK

**LOG**
```
[ancient-plains-6774][2016-02-17 08:25:37,114][ERROR] Instance doc lost, stopping server
  server_id = ObjectId('56b220dc35164b01e4285740')
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 784, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/helpers.py", line 38, in _wrapped
    for _ in call(*args, **kwargs):
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/instance.py", line 809, in _keep_alive_thread
    server_id=self.server.id,
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
```

**Comment by zachhuff386** [comment]
The query shown above is for a task that runs at an interval on one random host in the cluster to check the health of the servers. It's very unlikely for a cluster to have more then 10 severs. It wouldn't be reasonable to create an index for a single query that scans no more then 10 documents. The issues above have nothing to do with indexing as I explained in the other issue report you have major issues with server stability and network connectivity.

**Comment by US9IDX** [comment]
MongoDB What server should I use? Can you advise?
