### ISSUE TITLE
More verbose Pritunl Client errors

### ISSUE THREAD

**Issue by swozey** [pritunl/pritunl#257]
Recently began using Pritunl; looks great so far. 

One immediate issue is that the Pritunl client doesn't give any sort of error message when a connection has failed. In the UI, it just says Disconnected. I can look into the logs, but less technical users will just see that it gets immediately disconnected and ask whats going on. I tested this by disabling an account and attempting to connect with it. I then tested the same actions using Tunnelblick and Tunnelblick, when disconnected, immediately popped up something along the lines of "User authentication failed."

I think it'd be great for usability if the client parsed the error log and echoed at least a portion of it.

**Comment by zachhuff386** [comment]
There is plans to improve the connection errors in both the Linux and OSX/Windows client.
