### ISSUE TITLE
Pritunl settings missing

### ISSUE THREAD

**Issue by vmindru** [pritunl/pritunl#259]
Pritunl settings look like this http://i.imgur.com/UhdyCvX.png instead of looking like this as found in most of tutorials/reviews/showcases I have found  e.g.  http://i.imgur.com/Elzr2ka.png 

root@ip-10-10-0-108:~# pritunl version
pritunl v1.16.884.17
root@ip-10-10-0-108:~#

**Comment by zachhuff386** [comment]
Several settings were removed when support for multiple administrators was added to Enterprise.
