### ISSUE TITLE
ERROR Management socket exception

### ISSUE THREAD

**Issue by US9IDX** [pritunl/pritunl#269]
[autumn-thunder-6474] Options error: In [CMD-LINE]:1: Error opening configuration file: /tmp/pritunl_c24dacb444474285ab05812f882c29b2/3295567faad0482481ffd4c488b644dc/openvpn.conf
[autumn-thunder-6474] Use --help for more information.
[autumn-thunder-6474] Sun Mar  6 14:19:35 2016 ERROR Management socket exception
[autumn-thunder-6474] Options error: In [CMD-LINE]:1: Error opening configuration file: /tmp/pritunl_c24dacb444474285ab05812f882c29b2/de98166d50084cc3b71f0d23a846c59e/openvpn.conf
[autumn-thunder-6474] Use --help for more information.
[autumn-thunder-6474] Options error: In [CMD-LINE]:1: Error opening configuration file: /tmp/pritunl_c24dacb444474285ab05812f882c29b2/aa9408e9c4c342398a71bf117c4b649e/openvpn.conf
[autumn-thunder-6474] Use --help for more information.
[autumn-thunder-6474] Sun Mar  6 14:20:15 2016 ERROR Management socket exception
[autumn-thunder-6474] Sun Mar  6 14:20:24 2016 ERROR Management socket exception
[autumn-thunder-6474] Options error: In [CMD-LINE]:1: Error opening configuration file: /tmp/pritunl_c24dacb444474285ab05812f882c29b2/20844ba0fc7b4607b8ba03165faacecc/openvpn.conf
[autumn-thunder-6474] Use --help for more information.
[autumn-thunder-6474] Options error: In [CMD-LINE]:1: Error opening configuration file: /tmp/pritunl_c24dacb444474285ab05812f882c29b2/54cc80a4b59f4da38baa7bd91477b4a6/openvpn.conf
[autumn-thunder-6474] Use --help for more information.
[autumn-thunder-6474] Sun Mar  6 14:21:20 2016 ERROR Management socket exception
[autumn-thunder-6474] Options error: In [CMD-LINE]:1: Error opening configuration file: /tmp/pritunl_c24dacb444474285ab05812f882c29b2/b1c0621a554645ae9ae15cf1b9656a3a/openvpn.conf
[autumn-thunder-6474] Use --help for more information.

**Comment by zachhuff386** [comment]
Need information from the Pritunl logs not just the vpn logs.
