### ISSUE TITLE
Server Mode missing

### ISSUE THREAD

**Issue by dimspanos** [pritunl/pritunl#270]
I downloaded the latest version (free product)  and deployed to but when I choose to create a new Server the _Server Mode_ option doesn't appear, so I can't choose between local traffic and full pass-through. Any clues? 

The OS is Ubuntu 14.04 4-bit. 

Thanks in advance.

**Comment by zachhuff386** [comment]
Server mode has been replaced with the routes interface. A new server will default to what was all internet traffic mode which uses the `0.0.0.0/0` route. For local traffic only remove the `0.0.0.0/0` route and add local networks to the routes. For vpn only remove all the routes.
