### ISSUE TITLE
Slow TCP Connection

### ISSUE THREAD

**Issue by Fattur** [pritunl/pritunl#274]
This is a follow up issue of https://github.com/pritunl/pritunl/issues/273 (the answer is inappropriate and issue should not be closed @zachhuff386 )

On tcp connection is really slow. on udp it's fine but if i change it to tcp it suddenly drops to 3-4 mbit area and never gets any faster.  I am using tcp because I have to. And I have to use tcp because udp is completely blocked in some areas. So using udp is imposibble. And TCP is really slow.

**Comment by zachhuff386** [comment]
Duplicate: https://github.com/pritunl/pritunl/issues/273
