### ISSUE TITLE
How to change web port

### ISSUE THREAD

**Issue by psycholyzern** [pritunl/pritunl#277]
I am using tcp 443 for my vpn connection. 
Then I did an upgrade a while ago (pritunl v1.19.912.44), and vpn at port 443 wont work anymore because already used for webserver.
How to change back the port to 9700? I already modified file ```/etc/pritunl.conf``` and restart pritunl, but the webserver still working on port 443

**Comment by psycholyzern** [comment]
Solved. Need to change the port in ```/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/settings/app.py```

**Comment by zachhuff386** [comment]
Run the command `pritunl set app.server_port 9700` and modify `/etc/pritunl.conf` to set the port for the initial setup server.

**Comment by psycholyzern** [comment]
Ok. Thanks for the proper way of the port setup :)
