### ISSUE TITLE
Feature request: Customize DH parameter and Cipher Suits

### ISSUE THREAD

**Issue by FireUponSky** [pritunl/pritunl#280]
Hi, I'm using pritunl since the very beginning, thanks for making such a great project.

Yet generating long safe DH-parameter is very slow, It will be very convenient if it can use pregenerated parameters.

The other feature I request is adding an option to config cipher suits like `--tls-cipher` option of openvpn. This will allow us to disable weak ciphers or enforce security features like PFS.

Thank you.

**Comment by zachhuff386** [comment]
1536 bit DH parameters are pooled more information on the pooling system can be found here http://docs.pritunl.com/docs/infrastructure#resource-pooling-system

**Comment by zachhuff386** [comment]
Custom parameters are now available with the plugin system.
