### ISSUE TITLE
Multiple Devices

### ISSUE THREAD

**Issue by US9IDX** [pritunl/pritunl#282]
Hello.

I have 18 servers in 9 countries around the world.
Despite the fact that I forbade Multiple Devices (Disabled) the same user can connect to different servers.
So one user to connect 3 devices but on different servers.

I think it is necessary to amend limits not only servers, but also for users.
I think you need to do to enable and disable Multiple Devitses users, not just servers.

And it would be desirable to be able to impose restrictions on the number of devices that can be simultaneously connected to a single user.

Naprimetr it would be nice if it was possible to leave the value 5 devices simultaneously. Specify the number of devices not only for servers, but also for users.
Since users choose different server and connect despite the fact that the simultaneous connection of several devices is prohibited.

**Comment by zachhuff386** [comment]
Multiple devices will only be limited on single servers.

**Comment by US9IDX** [comment]
You can add the ability to restrict users on the device, rather than servers?

**Comment by zachhuff386** [comment]
There isn't going to be any additional features related to restricting multiple user connections. There isn't a significant use case for the feature.
