### ISSUE TITLE
ERROR Management socket exception

### ISSUE THREAD

**Issue by US9IDX** [pritunl/pritunl#283]
Hello.
Previously, I used one port 443 on all servers. Despite the fact that this can not be done from the web console, I edited the port-based MongoDB data and I did it installed on all servers on port 443. Error debts.
But now with the new version Pritunl servers refuse to work with the same port 443. Why do you remove that possibility?
It was the most convenient service when all servers are allowed to use the same port 443.
Now all customers will complain, as their providers are prohibited from using any ports other than 443.

----
[lively-plains-8407] Mon Mar 14 09:18:01 2016 ERROR Management socket exception
[lively-plains-8407] Mon Mar 14 09:18:00 2016 OpenVPN 2.3.10 x86_64-redhat-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jan  4 2016
[lively-plains-8407] Mon Mar 14 09:18:00 2016 library versions: OpenSSL 1.0.1e-fips 11 Feb 2013, LZO 2.06
[lively-plains-8407] Mon Mar 14 09:18:00 2016 Control Channel Authentication: tls-auth using INLINE static key file
[lively-plains-8407] Mon Mar 14 09:18:00 2016 TCP/UDP: Socket bind failed on local address [undef]: Address already in use
[lively-plains-8407] Mon Mar 14 09:18:00 2016 Exiting due to fatal error

**Comment by zachhuff386** [comment]
First change the port in `/etc/pritunl.conf` then run the command `pritunl set app.server_port 9700`

**Comment by US9IDX** [comment]
Status: Online
Uptime:3d 14h 9m 42s
Users: 11/1355 users online
Devices: 11 devices online
Network: 10.56.0.0/16
**Port: 443/tcp**
Multiple Devices: Disabled

I mean the server port and protocol
Previously, it was possible to show the same port for all servers via MongoDB editor. But in the new version Pritunl no such possibility.

**Comment by josegonzalez** [comment]
I had this issue and it turned out there was an orphaned openvpn server. Killing that process and restarting the vpn server from pritunl made everything better.
