### ISSUE TITLE
No options Pritunl local traffic

### ISSUE THREAD

**Issue by Kaerude** [pritunl/pritunl#286]
No options Pritunl local traffic ???

**Comment by zachhuff386** [comment]
Server mode and local networks have been replaced with the routes interface. Adding a route will tunnel traffic for the local network specified. The route `0.0.0.0/0` will route all internet traffic.

**Comment by Kaerude** [comment]
SO， local traffic Options need money?

**Comment by zachhuff386** [comment]
No routes can be added without a subscription.
