### ISSUE TITLE
Authentication code seems broken in latest pritunl

### ISSUE THREAD

**Issue by josegonzalez** [pritunl/pritunl#288]
Hi! We were using an (ancient) version of pritunl from last year, and recently upgraded. Our code for authentication seems to be broken against the latest version, even though a cursory glance at the codebase seems to confirm that it should. This is what used to work in php:

```php
$baseUrl = 'https://pritunl.example.com';
$apiToken = 'ADMIN_TOKEN';
$apiSecret = 'ADMIN_SECRET';

$authTimestamp = time();
$authNonce = $this->generateNonce();
$authString = implode('&', array(
    $apiToken,
    $authTimestamp,
    $authNonce,
    strtoupper('GET'),
    $endpoint,
));

$authSignature = base64_encode(hash_hmac('sha256', $authString, $apiSecret, true));

return Requests::get(sprintf('%s%s', $baseUrl, $endpoint), array(
    'Auth-Token' => $apiToken,
    'Auth-Timestamp' => $authTimestamp,
    'Auth-Nonce' => $authNonce,
    'Auth-Signature' => $authSignature,
    'Content-Type' => 'application/json',
));
```

With the latest version, we get `401 Unauthorized` back from pritunl.

Do you have an example of authentication working (even in another language)? I don't know how else to file an enterprise support ticket, but happy to move this to a more appropriate venue.

Thanks in advance!

**Comment by zachhuff386** [comment]
The api token is has moved to the administrators page and must be enable by editing an administrator.

**Comment by xUmaRix** [comment]
@josegonzalez 

I managed to get it work with the latest pritunl version.
You need to get the api token and secret from administrators table via mongodb.
Next you also need to change auth_api from false to true

`> db.administrators.find()
{ "_id" : ObjectId("57032b263e21ab552154a5df"), "username" : "admin", "password" : "2$=$//==", "auth_api" : true, "otp_secret" : null, "sessions" : [ "", "", "", "", "", "", "", "", "" ], "default" : null, "secret" : "", "super_user" : true, "disabled" : null, "token" : "", "otp_auth" : null }`
