### ISSUE TITLE
seems pritunl is a bit broken, or whats missing

### ISSUE THREAD

**Issue by svkamp** [pritunl/pritunl#290]
[calm-forest-8533] Thu Mar 17 14:43:10 2016 Server conf:
[calm-forest-8533] Thu Mar 17 14:43:10 2016   port 11726
[calm-forest-8533] Thu Mar 17 14:43:10 2016   proto udp
[calm-forest-8533] Thu Mar 17 14:43:10 2016   dev tun11
[calm-forest-8533] Thu Mar 17 14:43:10 2016   server 192.168.249.0 255.255.255.0
[calm-forest-8533] Thu Mar 17 14:43:10 2016   management /var/run/pritunl_56eafabeea2baa0289e463a2.sock unix
[calm-forest-8533] Thu Mar 17 14:43:10 2016   management-client-auth
[calm-forest-8533] Thu Mar 17 14:43:10 2016   auth-user-pass-optional
[calm-forest-8533] Thu Mar 17 14:43:10 2016   topology subnet
[calm-forest-8533] Thu Mar 17 14:43:10 2016   max-clients 4096
[calm-forest-8533] Thu Mar 17 14:43:10 2016   ping 10
[calm-forest-8533] Thu Mar 17 14:43:10 2016   ping-restart 80
[calm-forest-8533] Thu Mar 17 14:43:10 2016   push "ping 10"
[calm-forest-8533] Thu Mar 17 14:43:10 2016   push "ping-restart 60"
[calm-forest-8533] Thu Mar 17 14:43:10 2016   persist-tun
[calm-forest-8533] Thu Mar 17 14:43:10 2016   cipher AES-256-CBC
[calm-forest-8533] Thu Mar 17 14:43:10 2016   auth SHA256
[calm-forest-8533] Thu Mar 17 14:43:10 2016   status-version 2
[calm-forest-8533] Thu Mar 17 14:43:10 2016   script-security 2
[calm-forest-8533] Thu Mar 17 14:43:10 2016   reneg-sec 2592000
[calm-forest-8533] Thu Mar 17 14:43:10 2016   hash-size 1024 1024
[calm-forest-8533] Thu Mar 17 14:43:10 2016   max-routes-per-client 512
[calm-forest-8533] Thu Mar 17 14:43:10 2016   verb 4
[calm-forest-8533] Thu Mar 17 14:43:10 2016   mute 8
[calm-forest-8533] Thu Mar 17 14:43:10 2016   local 164.132.218.220
[calm-forest-8533] Thu Mar 17 14:43:10 2016   client-to-client
[calm-forest-8533] Thu Mar 17 14:43:10 2016   duplicate-cn
[calm-forest-8533] Thu Mar 17 14:43:10 2016   replay-window 128
[calm-forest-8533] Thu Mar 17 14:43:10 2016   comp-lzo no
[calm-forest-8533] Thu Mar 17 14:43:10 2016   push "comp-lzo no"
[calm-forest-8533] Options error: In [CMD-LINE]:1: Error opening configuration file: /tmp/pritunl_5aa16e3c31be4aec89c0c281c2a03ed4/6dd12f55b9144e118318403e9a780f5d/openvpn.conf
[calm-forest-8533] Use --help for more information.
[calm-forest-8533] Thu Mar 17 14:43:11 2016 ERROR Management socket exception
[calm-forest-8533] Thu Mar 17 14:43:20 2016 Server conf:
[calm-forest-8533] Thu Mar 17 14:43:20 2016   port 11726
[calm-forest-8533] Thu Mar 17 14:43:20 2016   proto udp
[calm-forest-8533] Thu Mar 17 14:43:20 2016   dev tun10
[calm-forest-8533] Thu Mar 17 14:43:20 2016   server 192.168.249.0 255.255.255.0
[calm-forest-8533] Thu Mar 17 14:43:20 2016   management /var/run/pritunl_56eafac8ea2baa0289e463cb.sock unix
[calm-forest-8533] Thu Mar 17 14:43:20 2016   management-client-auth
[calm-forest-8533] Thu Mar 17 14:43:20 2016   auth-user-pass-optional
[calm-forest-8533] Thu Mar 17 14:43:20 2016   topology subnet
[calm-forest-8533] Thu Mar 17 14:43:20 2016   max-clients 4096
[calm-forest-8533] Thu Mar 17 14:43:20 2016   ping 10
[calm-forest-8533] Thu Mar 17 14:43:20 2016   ping-restart 80
[calm-forest-8533] Thu Mar 17 14:43:20 2016   push "ping 10"
[calm-forest-8533] Thu Mar 17 14:43:20 2016   push "ping-restart 60"
[calm-forest-8533] Thu Mar 17 14:43:20 2016   persist-tun
[calm-forest-8533] Thu Mar 17 14:43:20 2016   cipher AES-256-CBC
[calm-forest-8533] Thu Mar 17 14:43:20 2016   auth SHA256
[calm-forest-8533] Thu Mar 17 14:43:20 2016   status-version 2
[calm-forest-8533] Thu Mar 17 14:43:20 2016   script-security 2
[calm-forest-8533] Thu Mar 17 14:43:20 2016   reneg-sec 2592000
[calm-forest-8533] Thu Mar 17 14:43:20 2016   hash-size 1024 1024
[calm-forest-8533] Thu Mar 17 14:43:20 2016   max-routes-per-client 512
[calm-forest-8533] Thu Mar 17 14:43:20 2016   verb 4
[calm-forest-8533] Thu Mar 17 14:43:20 2016   mute 8
[calm-forest-8533] Thu Mar 17 14:43:20 2016   local 164.132.218.220
[calm-forest-8533] Thu Mar 17 14:43:20 2016   client-to-client
[calm-forest-8533] Thu Mar 17 14:43:20 2016   duplicate-cn
[calm-forest-8533] Thu Mar 17 14:43:20 2016   replay-window 128
[calm-forest-8533] Thu Mar 17 14:43:20 2016   comp-lzo no
[calm-forest-8533] Thu Mar 17 14:43:20 2016   push "comp-lzo no"
[calm-forest-8533] Options error: In [CMD-LINE]:1: Error opening configuration file: /tmp/pritunl_5aa16e3c31be4aec89c0c281c2a03ed4/83de79d39c09464cbcd44a32ee353988/openvpn.conf
[calm-forest-8533] Use --help for more information.
[calm-forest-8533] Thu Mar 17 14:43:21 2016 ERROR Management socket exception
[calm-forest-8533] Thu Mar 17 14:43:31 2016 ERROR Management socket exception
[calm-forest-8533] Thu Mar 17 14:43:40 2016 Server conf:
[calm-forest-8533] Thu Mar 17 14:43:40 2016   port 11726
[calm-forest-8533] Thu Mar 17 14:43:40 2016   proto udp
[calm-forest-8533] Thu Mar 17 14:43:40 2016   dev tun97
[calm-forest-8533] Thu Mar 17 14:43:40 2016   server 192.168.249.0 255.255.255.0
[calm-forest-8533] Thu Mar 17 14:43:40 2016   management /var/run/pritunl_56eafadcea2baa0289e463fb.sock unix
[calm-forest-8533] Thu Mar 17 14:43:40 2016   management-client-auth
[calm-forest-8533] Thu Mar 17 14:43:40 2016   auth-user-pass-optional
[calm-forest-8533] Thu Mar 17 14:43:40 2016   topology subnet
[calm-forest-8533] Thu Mar 17 14:43:40 2016   max-clients 4096
[calm-forest-8533] Thu Mar 17 14:43:40 2016   ping 10
[calm-forest-8533] Thu Mar 17 14:43:40 2016   ping-restart 80
[calm-forest-8533] Thu Mar 17 14:43:40 2016   push "ping 10"
[calm-forest-8533] Thu Mar 17 14:43:40 2016   push "ping-restart 60"
[calm-forest-8533] Thu Mar 17 14:43:40 2016   persist-tun
[calm-forest-8533] Thu Mar 17 14:43:40 2016   cipher AES-256-CBC
[calm-forest-8533] Thu Mar 17 14:43:40 2016   auth SHA256
[calm-forest-8533] Thu Mar 17 14:43:40 2016   status-version 2
[calm-forest-8533] Thu Mar 17 14:43:40 2016   script-security 2
[calm-forest-8533] Thu Mar 17 14:43:40 2016   reneg-sec 2592000
[calm-forest-8533] Thu Mar 17 14:43:40 2016   hash-size 1024 1024
[calm-forest-8533] Thu Mar 17 14:43:40 2016   max-routes-per-client 512
[calm-forest-8533] Thu Mar 17 14:43:40 2016   verb 4
[calm-forest-8533] Thu Mar 17 14:43:40 2016   mute 8
[calm-forest-8533] Thu Mar 17 14:43:40 2016   local 164.132.218.220
[calm-forest-8533] Thu Mar 17 14:43:40 2016   client-to-client
[calm-forest-8533] Thu Mar 17 14:43:40 2016   duplicate-cn
[calm-forest-8533] Thu Mar 17 14:43:40 2016   replay-window 128
[calm-forest-8533] Thu Mar 17 14:43:40 2016   comp-lzo no
[calm-forest-8533] Thu Mar 17 14:43:40 2016   push "comp-lzo no"
[calm-forest-8533] Options error: In [CMD-LINE]:1: Error opening configuration file: /tmp/pritunl_5aa16e3c31be4aec89c0c281c2a03ed4/d29a313bc3ff43519cff4d2b5ee58b57/openvpn.conf
[calm-forest-8533] Use --help for more information.

**Comment by zachhuff386** [comment]
Check the logs by clicking Logs in the top right
