### ISSUE TITLE
OpenVPN client and Pritunl

### ISSUE THREAD

**Issue by syngent** [pritunl/pritunl#291]
Just installed 1.20 on ubuntu.  I am able to install the openvpn client on a Mac and authenticate without any issues.  Openvpn on PC's cannot authenticate.  Server logs states 'invalid pin'.  When we remove the pin from the user account, it authenticates fine.  Thought it may be the windows 7 pro 64-bit but we tried on multiple PC with the same issue.  Any advise or something Im overlooking?

Thanks, Perry

**Comment by zachhuff386** [comment]
The new release should fix any issues with passwords and pins
