### ISSUE TITLE
Limit bandwidth.

### ISSUE THREAD

**Issue by k0nsl** [pritunl/pritunl#294]
The only thing I'm missing in Pritunl is the possibility to individually limit bandwidth per user, or per organisation. That would be a useful feature, particularly in cases where you deploy a Pritunl server which has bandwidth limits. Alas, with the possibility to set a limit to bandwidth there would be no risk of overages, etc,.

**Comment by zachhuff386** [comment]
There isn't any plans to add bandwidth limits in pritunl.
