### ISSUE TITLE
Pritunl Client - fails to connect UBUNTU 

### ISSUE THREAD

**Issue by vmindru** [pritunl/pritunl#298]
Wen using the clinet, it fails to authentificate. 
When running the client from console  i can see 2 issues

1) The client is prompting for questions ( this is not visible when starting other wdm launcher )
2) The client fails to add routes 

vmindru@vmhodesk:/var/log$ pritunl-client-gtk 
[2016-03-23 22:56:37,185][INFO] Failed to sync conf, no subscription
  server_id   = u''
  user_id     = u''
  status_code = 480
  org_id      = u''
  sync_host   = u'https://:443'
  sync_hosts  = [u'https://:443']
  sync_hash   = u''
==== AUTHENTICATING FOR com.pritunl.client.profile_start ===
Authentication is required to start a connection
Multiple identities can be used for authentication:
 1.  mindru,,, (mindru)
 2.  Veaceslav,,, (vmindru)
Choose identity to authenticate as (1-2): 2
Password: 
==== AUTHENTICATION COMPLETE ===
Wed Mar 23 22:56:52 2016 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
Wed Mar 23 22:56:52 2016 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Wed Mar 23 22:56:52 2016 Control Channel Authentication: tls-auth using INLINE static key file
Wed Mar 23 22:56:52 2016 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed Mar 23 22:56:52 2016 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Wed Mar 23 22:56:52 2016 UDPv4 link local: [undef]
Wed Mar 23 22:56:52 2016 UDPv4 link remote: [AF_INET]:25000
Wed Mar 23 22:56:52 2016 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Wed Mar 23 22:56:54 2016 VERIFY OK: depth=1, O=, CN=
Wed Mar 23 22:56:54 2016 Validating certificate key usage
Wed Mar 23 22:56:54 2016 ++ Certificate has key usage  00a0, expects 00a0
Wed Mar 23 22:56:54 2016 NOTE: --mute triggered...
Wed Mar 23 22:56:58 2016 10 variation(s) on previous 3 message(s) suppressed by --mute
Wed Mar 23 22:56:58 2016 [] Peer Connection Initiated with [AF_INET]:25000
Wed Mar 23 22:57:00 2016 TUN/TAP device tun0 opened
Wed Mar 23 22:57:00 2016 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Wed Mar 23 22:57:00 2016 /sbin/ip link set dev tun0 up mtu 1500
Wed Mar 23 22:57:00 2016 /sbin/ip addr add dev tun0 192.168.237.2/24 broadcast 192.168.237.255
Wed Mar 23 22:57:00 2016 /usr/share/pritunl_client/update-resolv-conf.sh tun0 1500 1570 192.168.237.2 255.255.255.0 init
dhcp-option DNS 8.8.8.8
Wed Mar 23 22:57:00 2016 ERROR: Linux route add command failed: external program exited with error status: 2
Wed Mar 23 22:57:00 2016 ERROR: Linux route add command failed: external program exited with error status: 2
Wed Mar 23 22:57:00 2016 Initialization Sequence Completed

**Comment by zachhuff386** [comment]
I'm not able to reproduce this issue it appears to be an issue with your system

**Comment by pylemon** [comment]
I have the same problem here, after a while I found that it was due to my pritunl-client-gtk is not running on root user. It failed to run some commands which needs root privilege.
Fri Apr 22 18:49:43 2016 /sbin/ip link set dev tun0 up mtu 1500
Fri Apr 22 18:49:43 2016 /sbin/ip addr add dev tun0 10.10.0.7/22 broadcast 10.10.3.255
Fri Apr 22 18:49:43 2016 /usr/share/pritunl_client/update-resolv-conf.sh tun0 1500 1570 10.10.0.7 255.255.252.0 init

@vmindru 
Try running using sudo
 `$ sudo pritunl-client-gtk`
