### ISSUE TITLE
Feature request: bypass VPN fingerprint detection

### ISSUE THREAD

**Issue by sankros** [pritunl/pritunl#300]
Hey!
Right now sites may determine visitors with standard vpn config and block access to their servers.
For example, these websites easily define vpn users (tested on several pritunl configs on different OS)
[http://witch.valdikss.org.ru/](http://witch.valdikss.org.ru/)
[https://2ip.io/privacy/](https://2ip.io/privacy/)

This is due to the MTU/MSS value.
[A detailed article about this](https://medium.com/@ValdikSS/detecting-vpn-and-its-configuration-and-proxy-users-on-the-server-side-1bcc59742413#.1xryffsvo)
[Original article with author comments](https://translate.google.com/translate?sl=ru&tl=en&js=y&prev=_t&hl=ru&ie=UTF-8&u=http%3A%2F%2Fhabrahabr.ru%2Fpost%2F216295%2F&edit-text=)

It would be awesome to avoid VPN definition using pritunl.

Sincerely.

**Comment by zachhuff386** [comment]
There isn't a significant enough use case for this feature and there won't be any plans on adding it in a future release.
