### ISSUE TITLE
pritunl won't open after install on  Ubuntu 14.04.4 x64   

### ISSUE THREAD

**Issue by hardzink** [pritunl/pritunl#303]
curl --insecure https://localhost:9700/
curl: (7) Failed to connect to localhost port 9700: Connection refused

**Comment by zachhuff386** [comment]
The default port is now `443` more information on changing the port can be found here http://docs.pritunl.com/docs/configuration-5

**Comment by hardzink** [comment]
now ok.
thank you so much...
