### ISSUE TITLE
[question] Server mode in version v1.21.928.27

### ISSUE THREAD

**Issue by thebenwaters** [pritunl/pritunl#306]
How do I switch the server mode like in the tutorial below
![1-jgsroctkg1excj0lajwdqa](https://cloud.githubusercontent.com/assets/696445/14279423/d42460ca-fb35-11e5-986f-d4e370a858c3.png)

I don't see the option and my clients aren't able to connect to the standard internet.

**Comment by zachhuff386** [comment]
Duplicate https://github.com/pritunl/pritunl/issues/286
