### ISSUE TITLE
[bug] letsencrypt chain issues

### ISSUE THREAD

**Issue by thebenwaters** [pritunl/pritunl#307]
After a few hours and the certificate renews there are chian issues
<img width="456" alt="screen shot 2016-04-05 at 19 06 53" src="https://cloud.githubusercontent.com/assets/696445/14288981/9a4875b8-fb61-11e5-86c4-047fde1d2986.png">

**Comment by zachhuff386** [comment]
Duplicate https://github.com/pritunl/pritunl/issues/221
