### ISSUE TITLE
cannot remote after update package

### ISSUE THREAD

**Issue by hardzink** [pritunl/pritunl#308]

 
Hmm, we can't reach this page.

Try this
•Make sure you’ve got the right web address: https://xx.xx.xx.xx:9700
•Refresh the page
•Search for what you want

**Comment by hardzink** [comment]
Hmm, we can't reach this page.

Try this
 •Make sure you’ve got the right web address: https://128.199.65.98:443
 •Refresh the page
 •Search for what you want

**Comment by hardzink** [comment]
{
    "mongodb_uri": "mongodb://localhost:27017/pritunl",
    "log_path": "/var/log/pritunl.log",
    "static_cache": true,
    "temp_path": "/tmp/pritunl_8eb05d15038e41f6a35ef2043e1deec8",
    "bind_addr": "0.0.0.0",
    "debug": false,
    "www_path": "/usr/share/pritunl/www",
    "local_address_interface": "auto",
    "port": 443
}

**Comment by hardzink** [comment]
what should I do?

**Comment by iJebus** [comment]
In a possibly/probably? related case, doing a clean install of Pritunl on Ubuntu Server 14.04.4 LTS via the script in the documentation and I'm unable to connect.

**Comment by hardzink** [comment]
can u give me step?

**Comment by hardzink** [comment]
root@ubuntu-1GB-sgp1-01:~# service pritunl start
start: Job is already running: pritunl

**Comment by teamfighter** [comment]
I have tried fresh install, and now I cant even connect to pritunl:
openssl s_client -connect 192.168.3.165:443
CONNECTED(00000003)
140640265954960:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:795:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 261 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE

Looks like SSL problem, and installation package is totally broken.

**Comment by teamfighter** [comment]
Just checked out another fresh instance, Centos 7, installing from scratch.
The same result.
This bug is CRITICAL!

**Comment by zero9911** [comment]
I have tried fresh install, and now I cant even connect to pritunl:
openssl s_client -connect 192.168.3.165:443
CONNECTED(00000003)
140640265954960:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:795:
no peer certificate available
No client certificate CA names sent
SSL handshake has read 7 bytes and written 261 bytes
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE

Looks like SSL problem, and installation package is totally broken.


I also get this problem

**Comment by zachhuff386** [comment]
Duplicate #310
