### ISSUE TITLE
IPv6 connection issues

### ISSUE THREAD

**Issue by zero9911** [pritunl/pritunl#313]
my pritunl from server digitalocean (sg do ) and asiaonehost (sg gs )
before that i get problem 

" I have tried fresh install, and now I cant even connect to pritunl:
openssl s_client -connect 192.168.3.165:443
CONNECTED(00000003)
140640265954960:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:795:
no peer certificate available
No client certificate CA names sent
SSL handshake has read 7 bytes and written 261 bytes
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE "

after all has fix
my pritunl has no connection on my device "phone and tab" after new upgraded version "Pritunl v1.21.938.80"
I go to youtube, google like the internet is very slow off the beaten path
I use IPv6, TCP port 443
i also try port 91 tcp ipv6
so how?

**Comment by kedenya** [comment]
same my problem
lates version got problem no internet

i have old version, still working

**Comment by zero9911** [comment]
problem on ipv6 tcp only
i change server tu ipv4 udp it works totally

**Comment by animefreak93** [comment]
me too.. does't get any internet connection ipv6 :(
latest one

need help!

**Comment by zachhuff386** [comment]
Fixed in v1.21.941.39
