### ISSUE TITLE
Cannot login to the server dashboard. 

### ISSUE THREAD

**Issue by agottschling** [pritunl/pritunl#317]
After updating to the latest version, when I try to access the dashboard, my browser tries to download a file called login.bin. The download fails but the login screen never shows up.  Any ideas?

**Comment by Mandalavandalz** [comment]
Same here.

**Comment by zachhuff386** [comment]
What distro and is docker being used?

**Comment by Mandalavandalz** [comment]
Centos 7

**Comment by agottschling** [comment]
Ubuntu 14.04 and no Docker

**Comment by zachhuff386** [comment]
Try running the command `pritunl reset-ssl-cert`

**Comment by agottschling** [comment]
Didn't make a difference. However, if I manually navigate to `https://FQDN:9700/login`, the login screen shows up.

**Comment by zachhuff386** [comment]
What browser is being used?

**Comment by zachhuff386** [comment]
If your going to `http://domain:9700/` without https it will not work.

**Comment by Mandalavandalz** [comment]
No mater which browser i use it is downloading login.

**Comment by agottschling** [comment]
I always use https. Also,  it appears that the logout button is also broken.  The URL updates but it doesn't take me back to the login screen

**Comment by US9IDX** [comment]
I have the same problem!

**Comment by zachhuff386** [comment]
This will be fixed in v1.21.941.90 which will finish building in about 30 minutes. The command `sudo yum -y clean all` on CentOS when upgrading.
