### ISSUE TITLE
Setting routes on a server still makes 0.0.0.0/0 go to the VPN server

### ISSUE THREAD

**Issue by gerbilizer** [pritunl/pritunl#318]
After configuring the server and deleting the default route (0.0.0.0/0) and adding the network subnet (10.10.10.0/24) all internet traffic of the client is still being routed and dropped on the VPN server.

Am I doing something wrong?

I want Internet traffic to go to client's gateway and VPN traffic should go to the VPN server. Split tunnel.

**Comment by zachhuff386** [comment]
What distro and pritunl version is being used?

**Comment by gerbilizer** [comment]
Pritunl version is 1.21.942.24 running on CentOS 7 with iptables. 
The issue is on the client side. It still add a static route to the vpn gateway

**Comment by zachhuff386** [comment]
I can't reproduce this issue going to need more information.
