### ISSUE TITLE
Allow custom openvpn option for user download config in server settings.

### ISSUE THREAD

**Issue by hariesnurikhwan** [pritunl/pritunl#322]
I have like 100 users, I want to include http-remote-proxy and other options for that I have to download their config and modify and add the options in the configs manually.

I would be great if we could add a custom line openvpn options in the server settings so we wouldn't have to change it manually and that would save a lot of time.

**Comment by zachhuff386** [comment]
There isn't a significant use case for this so it likely won't be added.
