### ISSUE TITLE
How to use the same Pritunl console to manage different servers located in different countries?

### ISSUE THREAD

**Issue by kilobps** [pritunl/pritunl#324]
For example:
I have one server in UK with IP1, and one server in USA with IP2.
So then i need to deployment Pritunl server service software on each servers, then i will get 2 console.
But how to manage these 2 servers in the same console?

Because the issue is, if i want to deployment VPN servers that located in 10 countries, then i need 10 consoles? It's very crazy.

So appreciate that if you can answer my doubt.
Thank you so much.
I like Pritunl.

**Comment by zachhuff386** [comment]
The Enterprise subscription supports managing multiple servers in a cluster.
