### ISSUE TITLE
cannot access htpps://serverip:9700

### ISSUE THREAD

**Issue by hyreeckei** [pritunl/pritunl#325]
I am using Ubuntu server 14.04, why i cannot access "htpps://serverip:9700", its like something blocking it to access

**Comment by zachhuff386** [comment]
The default port has changed to 443

**Comment by hyreeckei** [comment]
i still cannot access it using "https:/serverip:443"

**Comment by yojo3000** [comment]
I think you shoud add default port number, account and password on the readme page
