### ISSUE TITLE
ERROR User auth failed "Invalid OTP code"

### ISSUE THREAD

**Issue by BabuVelu** [pritunl/pritunl#330]
Hello Support,

We are unable to login the MFA using the google authentication. Please see the below logs.

<Snip>
09:53:12 2016 TCP connection established with [AF_INET]59.163.207.174:54427
[calm-meadow-8520] Fri Apr 22 09:53:22 2016 ERROR User auth failed "Invalid OTP code"
[calm-meadow-8520] Fri Apr 22 09:53:22 2016 COM> SUCCESS: client-deny command succeeded
[calm-meadow-8520] Fri Apr 22 09:53:22 2016 59.163.207.174:54427 [57092bb52b376109d2fcf800] Peer Connection Initiated with [AF_INET]59.163.207.174:54427
[calm-meadow-8520] Fri Apr 22 09:53:25 2016 59.163.207.174:54427 Connection reset, restarting [0]
[calm-meadow-8520] Fri Apr 22 09:53:58 2016 TCP connection established with [AF_INET]59.163.207.174:54524
[calm-meadow-8520] Fri Apr 22 09:54:07 2016 ERROR User auth failed "Invalid OTP code"
[calm-meadow-8520] Fri Apr 22 09:54:07 2016 COM> SUCCESS: client-deny command succeeded
[calm-meadow-8520] Fri Apr 22 09:54:08 2016 59.163.207.174:54524 [57092bb52b376109d2fcf800] Peer Connection Initiated with [AF_INET]59.163.207.174:54524
[calm-meadow-8520] Fri Apr 22 09:54:11 2016 59.163.207.174:54524 Connection reset, restarting [0]

</Snip>

**Comment by zachhuff386** [comment]
The OTP code is invalid

**Comment by BabuVelu** [comment]
Thanks Support. It is working now. Pritunl support LDAP authentication ?.

**Comment by BabuVelu** [comment]
Any update on sso ldap support?
