### ISSUE TITLE
Pritunl Always disconnecting And need to be restart everytime

### ISSUE THREAD

**Issue by ainulasyraf** [pritunl/pritunl#331]
i have a problem which my pritunl server always disconnecting and need me to restart everything in order pritunl to works again.. Im using Ubuntu 14.04.4 x64..i need to restart until 3 -4 times a day..sometime not even 3 hours after i restarted pritunl it will not function once again..is there any way to solve this problem?im using automatic install on ubuntu.. Ty

**Comment by zachhuff386** [comment]
Check the server logs

**Comment by ainulasyraf** [comment]
how to check the server logs?

**Comment by ainulasyraf** [comment]
Echo Server - Version 1.0
=========================

General Parameters:
   Pool Handle             = EchoPool
   Reregistration Interval = 30.000s
   Local Addresses         = { all }
   Runtime Limit           = off
   Policy Settings
      Policy Type          = RoundRobin
      Load Degradation     = 0.000%
      Load DPF             = 0.000%
      Weight               = 0
      Weight DPF           = 0.000%
23-Apr-2016 10:48:50.7963: P2381.7f690a53f780@SERVERENOL
rserpoolsocket.c:354 doRegistration()
23-Apr-2016 10:48:50.7980: Error: (Re-)Registration failed: no registrar
available

**Comment by ainulasyraf** [comment]
how to solve this?

**Comment by zachhuff386** [comment]
This doesn't appear to be related to Pritunl
