### ISSUE TITLE
Incorrect redirect

### ISSUE THREAD

**Issue by teamfighter** [pritunl/pritunl#342]
I have setup my pritunl server and now I am testing google auth.
Web console is listening on port 8443.
When I am authentificating through google, pritunl redirects me from http**s**://x.x.x.x:8443 to http://x.x.x.x:8443. And this link is not working. 
That seems confusing. Help me please.
I am using pritunl-1.21.954.48-1.el7.centos.x86_64 and I cant configure webconsole on different port.

**Comment by teamfighter** [comment]
How could I fix this error now?

**Comment by teamfighter** [comment]
Guys, what I am paying for? I am paying 150$  in a month for 3 licenses, why dont you supporting? Anybody answer me, or I`ll cancel my license!

**Comment by zachhuff386** [comment]
The commit above fixed the issue. Replacing this line https://github.com/pritunl/pritunl/blob/5dc203681f11131987f0ed566771029ccb433344/pritunl/handlers/key.py#L582 with `callback = flask.request.url_root.replace('http://', 'https://') + 'sso/callback'` will fix the issue. The file is at `/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/handlers/key.py`. Opening port 80 for the redirect server will also fix the issue.

**Comment by teamfighter** [comment]
Thanks.

**Comment by teamfighter** [comment]
Still no luck. I have replaced line 582 in file `/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/handlers/key.py`, as followed with line `callback = flask.request.url_root.replace('http://', 'https://') + 'sso/callback'`, but I still dont have correct redirection

**Comment by zachhuff386** [comment]
You need to restart the service

**Comment by teamfighter** [comment]
I have even rebooted server.
