### ISSUE TITLE
Custom SSL Certificate

### ISSUE THREAD

**Issue by galindro** [pritunl/pritunl#350]
How could I install a custom SSL Certificate? This can't be done in settings as pointed by [docs](https://docs.pritunl.com/docs/custom-ssl-certificate).
I don't want to use LetsEncrypt.

![image](https://cloud.githubusercontent.com/assets/4622097/15270464/5c52fcf6-19f7-11e6-8155-1eaca9e35f5b.png)

**Comment by zachhuff386** [comment]
An Enterprise subscription is required for custom SSL certificates.
