### ISSUE TITLE
Very slow troughput and DNS on Win7

### ISSUE THREAD

**Issue by pilovali** [pritunl/pritunl#353]
I have several clients with Windows 7. They all have issues with DNS (unless static DNS) and very slow (slower than 1 Mbps) troughput. 
Clients with Win8+ don't have this issue.

**Comment by zachhuff386** [comment]
There isn't enough information to resolve this issue and I won't attempt to replicate bandwidth issues on Windows.

**Comment by pilovali** [comment]
What kind of information do you need?
