### ISSUE TITLE
Push DNS to clients

### ISSUE THREAD

**Issue by galindro** [pritunl/pritunl#355]
Pushing DNS to clients is an enterprise feature? I'm wondering this because I've configured the DNS server option in the server configuration from GUI, but it isn't sent to the clients. Investigating on the server, the temporary configuration doesn't contains the line push "dhcp-option DNS 10.0.0.2".

![image](https://cloud.githubusercontent.com/assets/4622097/15304755/7b7940e6-1b95-11e6-9752-f062e257fc8f.png)

**Comment by zachhuff386** [comment]
The DNS servers are pushed with the client configuration on connection.

**Comment by galindro** [comment]
OK but how could I do it? 
Where is the documentation related to it? 
Why the server configuration that I did isn't sufficient for doing my proupose?
AFAIK that option is necessary for push DNS server configuration to clients without any client intervention.
Could you please be more specific? I'm evaluating this tool and I need to know this in details before buy it.

**Comment by galindro** [comment]
@zachhuff386 there is no line on client config that push the DNS configuration.
There isn't a **dhcp-option DNS 10.0.0.2** line inside any client configuration downloaded from my pritunl server.
Please, reopen this case. I think this is a bug.

This is my pritunl server version:

```
# dpkg -l |grep pritun
ii  pritunl                                  1.21.967.90-0ubuntu1~trusty             all          Enterprise VPN Server

```

It is running on a Ubuntu 14.04.4 LTS Server

**Comment by zachhuff386** [comment]
https://github.com/pritunl/pritunl/blob/master/pritunl/clients/clients.py#L114

**Comment by galindro** [comment]
It is not working! I've already read this line before. It isn't generating the client config file with that parameter (push "dhcp-option DNS 10.0.0.2") and the dns_servers array with ['10.0.0.2'] value consts in mongodb.

How could I debug this to find the issue? If you want, I can give to you access to my server. But please, don't give me an answer that can't help me.

**Comment by galindro** [comment]
@zachhuff386 when that file is called? I could confirm by monitoring the filesystem that it isn't called when I click to download the user profile nor when I stop and start the server. Maybe I could put some debug info before that line.

**Comment by galindro** [comment]
@zachhuff386 even recreating the server, it don't generate the client config with push DNS

**Comment by zachhuff386** [comment]
The configuration above is never stored in a file it is sent to the client **on connection** after authentication occurs.
