### ISSUE TITLE
Push DNS to clients: Linux

### ISSUE THREAD

**Issue by galindro** [pritunl/pritunl#357]
@zachhuff386 plase read this before close it abruptly. This ticket is only a complement of https://github.com/pritunl/pritunl/issues/355.

Now I finally understand how printunl works with openvpn server process: it uses the [OpenVPN Management interface](https://openvpn.net/index.php/open-source/documentation/miscellaneous/79-management-interface.html). So, when a client establishes a connection, pritunl uses the management interface to push GUI-Specific parameters to the client. Very cool. 

It is working as expected, but on Linux no, probably because [this bug](https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1211110). This f...ing bug was blinding me. After testing it under a Windows station, everything worked fine even using the openvpn-gui. So, I suggest to you to put this information in a "troubleshooting section" on the documentation to help users avoid wasting time.

You can consider this post a help, or just ignore it and block this thread as you did in https://github.com/pritunl/pritunl/issues/355 and https://github.com/pritunl/pritunl/issues/356 (the last one I realy don't know why you did it...).

Maybe you could consider to put this project in a pivate repository of github to avoid things like it. But if you want to make it public, you must consider to be more kindness with people that are investing time to help/use your project and, more important, **want to buy it**.

Thank you again.

**Comment by zachhuff386** [comment]
Linux requires the use of scripts such as https://github.com/pritunl/pritunl-client/blob/master/data/scripts/update-resolv-conf.sh to handle DNS servers with OpenVPN.

**Comment by galindro** [comment]
Yes you are right.
