### ISSUE TITLE
Amazon AWS VPC site-to-site vpn

### ISSUE THREAD

**Issue by BabuVelu** [pritunl/pritunl#360]
Support, 

We are working with  the  AWS region to region VPN connection using the pritunl VPN. 

- We have configured the VPN both regions as per the doc link. "https://medium.com/pritunl-tutorials/pritunl-advanced-tutorial-2be5cc57dff8#.gc3ywal8j" . Now we are facing the issue while link the server. 

Error message " No servers exists, a server must be created before attaching." 

VPN region : US-West2 and EU-west1
Pritunl Version : pritunl-1.23.987.18-1.el7.centos.x86_64.

I need your input to configure the site-to-site vpn on AWS ec2.

Regards,
Babu

**Comment by zachhuff386** [comment]
Follow this tutorial https://docs.pritunl.com/docs/site-to-site-configuration
