### ISSUE TITLE
Site-to-Site Configuration

### ISSUE THREAD

**Issue by BabuVelu** [pritunl/pritunl#361]
Support, 

Hello support,

I have configured the site to site vpn using the link "https://docs.pritunl.com/docs/site-to-site-configuration". I got the following error message 

"Linked servers cannot have a common route."

I need your help to fix this issue.

VPC CIDR : 10.97.88.0/21 and 10.97.80.0/21 ( US-west2 to EU)

Regards,
Babu

**Comment by zachhuff386** [comment]
Linked servers cannot have the same routes. Each server should only have a route to the VPC network that the server is running on.
