### ISSUE TITLE
Error downloading Let's Encrypt challenge

### ISSUE THREAD

**Issue by mklatsky** [pritunl/pritunl#362]
This is similar to issue #358.

I am running pritunl v1.23.987.18.

When I enter my server name in the settings (for the Let's Encrypt generation), I receive the following error: Error getting LetsEncrypt certificate check the logs for more information.

From the logs: (with my server name obfuscated):

[thriving-meadow-4872][2016-05-31 13:30:06,432][ERROR] Failed to get LetsEncrypt cert
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/settings.py", line 532, in settings_put
    
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/acme.py", line 49, in update_acme_cert
    cert = get_acme_cert(settings.app.acme_key, csr)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/acme.py", line 24, in get_acme_cert
    app.set_acme,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/acme_tiny.py", line 139, in get_crt
    raise ValueError("Couldn't download {0}".format(wellknown_url))
ValueError: Couldn't download http://my.domain.com/.well-known/acme-challenge/oAax2ON5x55lmczpyylZct97-tN_VditRTHXwrqDh9M
  acme_domain = u'my.domain.com'

* port 80 is publicly accessible. 
* there is nothing running on port 80. 
* My server hostname resolves to the public IP address of my server. 
* The same hostname is used to access my admin console on port 9700
* my host does not sit behind any firewall

**Expected**: A valid Lets's Encrypt is generated and configured for my VPN server

**Comment by zachhuff386** [comment]
The error indicates the Lets Encrypt servers cannot reach the server on port 80. If the redirect server has been disabled Lets Encrypt can't be used. If the DNS record has recently been changed it can take a while for the record to update.

**Comment by mklatsky** [comment]
I believe I found the issue. My /etc/pritunl.conf file has:

{
    "mongodb_uri": "mongodb://localhost:27017/pritunl",
    "server_key_path": "/var/lib/pritunl/pritunl.key",
    "log_path": "/var/log/pritunl.log",
    "static_cache": true,
    "server_cert_path": "/var/lib/pritunl/pritunl.crt",
    "temp_path": "/tmp/pritunl_%r",
    "bind_addr": "0.0.0.0",
    "debug": false,
    "www_path": "/usr/share/pritunl/www",
    "local_address_interface": "auto",
    "port": 9700,
    "data_path": "/var/lib/pritunl"
}

When I changed "port": 9700 to "port": 80" - I was able to generate and download a certificate.
