### ISSUE TITLE
failed login with google authentication .

### ISSUE THREAD

**Issue by uavg** [pritunl/pritunl#366]
when i try to login pritunl with google authentication, it will always report:
> The connection was reset

and there is no related log in '/var/log/pritunl.log'. the url in brower is:
http://xxx/sso/callback?state=oMH0yv38KPSDyqevs0ltVZm7YKKUGQLwtn7aW63ARVJvNva18Fd4INqc2Ul14rrK&username=**t&sig=KW7MJYHpmBHCAaKjp37-5Pr--w3sqBe_uX5m8uEUMk__uIsRWO7wp8eOJfj8txSMQSaMWuhczONZ1E8ZV4bDhA%3D%3D

my pritunl version is： 
`pritunl-1.21.954.48-1.el7.centos.x86_64`

can you guys take a look on this issue? many thanks.

**Comment by zachhuff386** [comment]
This is from a redirection issue that was fixed in v1.21.967.90
