### ISSUE TITLE
Enterprise subscription + COMPOSE => Unknown server error occurred

### ISSUE THREAD

**Issue by kilobps** [pritunl/pritunl#368]
When i using Enterprise subscription and COMPOSE, it didn't work.
When i went to "pritunl database setup" step, it told me that:
_"Unknown server error occurred."_

BTW, i have tried this 2 links of COMPOSE:

- mongodb://<username>:<password>@aws-us-east-1-portal.11.dblayer.com:28123,aws-us-east-1-portal.10.dblayer.com:11397/gravityvpn?ssl=true

- mongodb://<username>:<password>@aws-us-east-1-portal.11.dblayer.com:28123/gravityvpn?ssl=true

Thanks so much.

**Comment by zachhuff386** [comment]
Check the output of `cat /var/logs/pritunl.log`

**Comment by zachhuff386** [comment]
The url above is missing a username and password. If the username and password was removed when posting this check the output of `cat /var/logs/pritunl.log` for the error.

**Comment by kilobps** [comment]
Thanks, by check the /var/log/pritunl.log, i found the reason.

- When I connect to COMPOSE server with SSL, it failed and feedback "Unknown server error occurred."
- When I connect to COMPOSE server withous SSL, it successed.

But now, i have an another question, how to adjust my Pritunl server so that they can connect to COMPOSE server with SSL successfully ?  I have searched for sometime, but I didn't found the exactly guide link, Can you please share it to me?  thanks very much.

**Comment by zachhuff386** [comment]
Compose does not use valid SSL certificates. You will need to download the certificate and add the file path to the MongoDB uri as shown here https://docs.pritunl.com/docs/configuration-5
