### ISSUE TITLE
Custom SSL cert kills webserver

### ISSUE THREAD

**Issue by jimcroft** [pritunl/pritunl#369]
I'm trying to apply a custom SSL cert but when I do the webserver fails.

I've confirmed the SSL key and cert is valid.

The logs show:

```
[evening-plains-3938][2016-06-07 12:41:57,311][ERROR] Web server process exited unexpectedly
Process stderr:
  panic: crypto/tls: failed to find any PEM data in key input

  goroutine 1 [running]:
  panic(0x7016c0, 0xc82000aec0)
  	/usr/local/go/src/runtime/panic.go:481 +0x3e6
  main.main()
  	/go/src/github.com/pritunl/pritunl-web/main.go:128 +0x492
```

The [docs on the subject of SSL certs](https://docs.pritunl.com/docs/custom-ssl-certificate) are very sparse and don't offer any pointers what the problem is. Any ideas?

**Comment by zachhuff386** [comment]
The custom SSL certificate documentation has been updated. The certificate option will need first include the certificate then any intermediates, and the CA's certificate.
