### ISSUE TITLE
Secondary authentication failure with OneLogin

### ISSUE THREAD

**Issue by jimcroft** [pritunl/pritunl#370]
Hi

I've setup Pritunl Enterprise to use OneLogin for auth. Logins to the WebUI work fine however the Pritunl client cannot connect users to the VPN. The error logged is:

`ERROR User auth failed "Failed secondary authentication"`

Any ideas?

I'm not 100% sure Pritunl is configured correctly for the OneLogin API. The Pritunl UI has a single field `OneLogin API Key` for hitting the OneLogin API however when generating API access credentials in OneLogin I get a `Client Secret` and a `Client ID`. I've tried both as the `OneLogin API Key` in Pritunl and the user auth failure persists.

Thanks

Jim

**Comment by zachhuff386** [comment]
Check the output of `pritunl logs` or look at the logs in the web console. The single sign-on integrations are regularly tested and there isn't any issues currently.
