### ISSUE TITLE
Remote MongoDB keep disconnect

### ISSUE THREAD

**Issue by ijat** [pritunl/pritunl#379]
Hi, Im using latest MongoDB and Pritunl from the repository. Tested on Ubuntu 14, 15 and Centos 6,7 but the problem still  #occur. The server keeps disconnect clients when using _remote MongoDB_, but works perfectly on _local installation_. Even show verbose/debug, only this error show without saying anything else:

`MANAGEMENT: CMD 'client-kill 5'`

This problem happen every 1 minute or less and keep repeating. Is it bug or misconfiguration? Thanks

**Comment by zachhuff386** [comment]
Not enough information was provided to solve this issue.
