### ISSUE TITLE
Server run error

### ISSUE THREAD

**Issue by g-arjones** [pritunl/pritunl#381]
When starting pritunl with several servers running at the same time sometimes some of these servers might have problems trying to get the default interface. I suspect this happens because some of them may be trying to these while a bridged one is still setting up routes and bridge. I think that syncing the threads in a way that the servers are started in sequence instead of in parallel would fix this. 

[winter-skies-6905][2016-06-22 07:49:00,640][ERROR] Server error occurred while running
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 741, in _run_thread
    self.generate_iptables_rules()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 330, in generate_iptables_rules
    raise IptablesError('Failed to find default network interface')
IptablesError: Failed to find default network interface
  server_id = ObjectId('56c24258f1ed120009dec06e')

Again, this only happens when they are started automatically, if I start them manually one at a time this doesn't happen.

**Comment by g-arjones** [comment]
I saw a "Fix app start" commit. Does it mean this bug is fixed? Thank you!

**Comment by g-arjones** [comment]
@zachhuff386 Any updates here? This bug is a major drawback in my company's use case since the only way to get everything working as expected is to start each server manually which is, of course, not practical. If you point me to the line where servers are instantiated and started I can fix it myself and submit a pull request or just get it working while you come up with a better solution. Thank you

**Comment by zachhuff386** [comment]
What is the use case for running multiple bridged servers on one host? This most likely won't be fixed, only one bridged server should run on each host.

**Comment by zachhuff386** [comment]
I've looked into this and running multiple bridged servers on one host shouldn't work. It will cause several issues due to conflicting configurations.

**Comment by g-arjones** [comment]
I am not running multiple bridged, just one bridged and one routed. It
works without a problem if I started them manually, the problem is when
they are started automatically. Sometimes the routed fails to get the
default iface because the bridged is still setting this up. It's a race
condition error.

**Comment by zachhuff386** [comment]
That configuration won't work either. There are several components that assume the default interface name won't change which will occur when starting the bridged server. You will need to manually start the bridged server first then the other servers or run the routed server on a different host. With the auto failover and replication system there is no way guarantee the order that servers are started it will need to be done manually.

**Comment by g-arjones** [comment]
What is the difference between me clicking "start server" on the bridged
and then "start server" on the routed or pritunl programatically making
sure it starts the bridged and then the other one?

1. Iterate through servers;
2. Find bridged;
3. Start bridged (acquires lock);
4. Start others (waits for lock to be released)

Could you please tell me where on the code instantiation and startup occurs
on pritunl initialization? There is no point in running a server that
requires manual initialization and having to instances of pritunl is not
really an option here. Last resort would be to writing a script using the
pritunl API to start them but I would rather  have the solution builtin.

**Comment by zachhuff386** [comment]
The auto failover and replication system can start and stop specific servers leading to a bridged server starting after a routed server.

**Comment by g-arjones** [comment]
Are there methods on the API to list servers, get status, stop and start?
