### ISSUE TITLE
Masquerade not working

### ISSUE THREAD

**Issue by dupersuper** [pritunl/pritunl#390]
Installing pritunl in Amazon Linux or Ubuntu, internet access for clients is not working. The installation documentation doesn't mention anything about adding "net.ipv4.ip_forward = 1" but I'm suppose that I must do that manually.

The output of  iptables -t nat -L shows me this:
Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
MASQUERADE  all  --  ip-192-168-249-0.eu-west-1.compute.internal/24  anywhere             /* pritunl

That should be the /24 of my subnet not the hostname of my instance.
I tested this behavior using Amazon Linux and Ubuntu 14.04.

**Comment by zachhuff386** [comment]
Running the command `iptables -t nat -L -n` will show the ip addresses. IP forwarding is automatically enabled.

**Comment by dupersuper** [comment]
Yeap, you are right. So, I don't even need to change the net.ipv4.ip_forward to 1, right? Without changing that, I can't even connect to my remote sites. Am I missing something here? Thanks

**Comment by dupersuper** [comment]
I was able to narrow down the problem to clients running ipv6 and ipv4. Since AWS doesn't support ipv6 and I wasn't having problems with OpenVPN appliance, what do you think it may be the problem? I tried enabling ipv6 in the server configuration but it failed to start it. Thank you
