### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by US9IDX** [pritunl/pritunl#391]
OS: Ubuntu 14.04 x 64

I have 21 server, all servers have the latest update v1.24.1019.41.
After I updated to version v1.24.1019.41 I could not go to the control panel as the get error 500.
Skrinshot: https://gyazo.com/6188729f28a8b56cf93a16b2fdc08870

root@Mongo:~# pritunl reset-version
Database version reset to 1.24.1019.41

I tried to roll back to version v1.23.1005.91 but MongoDB database is inconsistent.

Pritunl.log
```
[undefined][2016-06-28 13:17:58,153][INFO] Starting setup server
[undefined][2016-06-28 13:17:58,155][INFO] Generating setup server ssl cert
```
Now I can not log in to the web interface and can not install the previous version Pritonl as MongoDB data base has been updated to version v1.24.1019.41.

All that you described earlier I have done, but this did not lead to the result.
I tried to completely reinstall the operating system. I tried to put a different OS. The error is repeated.

If I set v1.23.1005.91 version of the web interface and do not have access to the error log shows that incompatible versions pritunl and databases.

**Comment by zachhuff386** [comment]
I have tested a 1.24.1019.41 to 1.23.1005.91 downgrade there are no issues. Any additional issues opened will be closed and ignored.

`apt-get install pritunl`

```
[undefined][2016-06-28 17:21:45,442][INFO] Starting setup server
[undefined][2016-06-28 17:21:45,448][INFO] Generating setup server ssl cert
[undefined][2016-06-28 17:23:11,359][INFO] Generating auth token
[undefined][2016-06-28 17:23:11,360][INFO] Generating auth secret
```

```
wget https://github.com/pritunl/pritunl/releases/download/1.23.1005.91/pritunl_1.23.1005.91-0ubuntu1.trusty_all.deb
dpkg -i pritunl_1.23.1005.91-0ubuntu1.trusty_all.deb
service pritunl restart
```

```
[undefined][2016-06-28 17:26:01,815][ERROR] Database version is newer than server version
  db_version     = 1002410194041
  server_version = 1002310054091
[undefined][2016-06-28 17:26:01,818][ERROR] Pritunl setup failed
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/__init__.py", line 32, in setup_all
    setup_server()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/server.py", line 254, in setup_server
    exit(75)
  File "/usr/lib/pritunl/lib/python2.7/site.py", line 403, in __call__
    raise SystemExit(code)
SystemExit: 75
```

```
pritunl reset-version
[undefined][2016-06-28 17:26:12,524][INFO] Setting db version
  new_ver = '1.23.1005.91'
  cur_ver = u'1.24.1019.41'
Database version reset to 1.23.1005.91
service pritunl restart
```
