### ISSUE TITLE
Android dont work when del ROUTE 0.0.0.0

### ISSUE THREAD

**Issue by Newcss** [pritunl/pritunl#394]
When delete ROUTE 0.0.0.0 android devices cant ping other devices connected to the Pritunl.
Windows clients work without problem.

**Comment by paulkramme** [comment]
Yes, its an old problem. Split tunneling does not work on Android.

**Comment by zachhuff386** [comment]
I can't reproduce any issues with routing networks on Android 6.0.1. What version are you using?
