### ISSUE TITLE
pritunl database setup

### ISSUE THREAD

**Issue by yunfuyuan** [pritunl/pritunl#398]
error：Setup key is invalid.

In step:pritunl database setup

How to solve this problem？ 
thank you！

**Comment by zachhuff386** [comment]
On the server run the command `pritunl setup-key` then copy the key the web console.

**Comment by yunfuyuan** [comment]
When I entered my key, click the Save button, web did not react, save button into a state can not be clicked

**Comment by zachhuff386** [comment]
I can't replicate this issue it is most likely related to the web browser.

**Comment by yunfuyuan** [comment]
I will try again, thank you.
