### ISSUE TITLE
Unable to bind server to address

### ISSUE THREAD

**Issue by paulg1981** [pritunl/pritunl#399]
Hello,
I have been using pritunl for a while now and I did a fresh install and setup pritunl. Everything works except when I try to bind a server specifically to one of the ips on the box. If I specify an ip I get this:

[snowy-dreams-2974] Sun Jul  3 18:32:45 2016 RESOLVE: Cannot resolve host address: <removed>: Address family for hostname not supported
[snowy-dreams-2974] Sun Jul  3 18:32:45 2016 Exiting due to fatal error
[snowy-dreams-2974] Sun Jul  3 18:32:46 2016 ERROR Management socket exception

I am using the numerical address and not a hostname. Nothing is listening on the port on that ip (443). I have never had any issue with binding or running a server on a specific ip before. Please Help!

Thanks for any direction you can provide.

**Comment by zachhuff386** [comment]
You'll need to disable IPv6 connections to bind to an address. Run `pritunl set vpn.ipv6 false`

**Comment by paulg1981** [comment]
Perfect, worked like a charm! I appreciate your help
