### ISSUE TITLE
does not start

### ISSUE THREAD

**Issue by CarlosPG84** [pritunl/pritunl#400]
HI all, 

I try to install in Ubuntu and Debian without lucky.

Can you help me?

root@debian:/opt/pritunl-master# pritunl start
/usr/bin/pritunl: line 3: __requires__: command not found
/usr/bin/pritunl: line 4: import: command not found
from: can't read /var/mail/pkg_resources
/usr/bin/pritunl: line 8: syntax error near unexpected token `newline'
/usr/bin/pritunl: line 8: `    sys.exit('
root@debian:/opt/pritunl-master#

**Comment by zachhuff386** [comment]
This is from an incorrect installation. Only the packages listed on the homepage are supported.
