### ISSUE TITLE
Multiple user in one config

### ISSUE THREAD

**Issue by PakTam** [pritunl/pritunl#402]
hey there.

im new in here.
i would like to ask.
is there a possible for multiple user to connect to the server with only one clients config.
but not multiple device?

example:

user1
user2
user3

using "Master.ovpn" to use the vpn?

**Comment by zachhuff386** [comment]
There isn't a significant enough use case for this feature and there won't be any plans on adding it in a future release.

**Comment by PakTam** [comment]
so then.
is there a way to edit client config other than download the config?.

and all clients config on a server will be edited?
certain edit for certain server..
