### ISSUE TITLE
DNS resolution from non TUN interface

### ISSUE THREAD

**Issue by centric-jim** [pritunl/pritunl#408]
DNS resolution for our VPN clients, VPN Client DNS Mapping, only resolves from the TUN interface.  

'dig host.example.vpn @tun0.ip.address' works

'dig host.example.vpn @eth0.ip.address' does not resolve/work.

I'd guess this is a feature request but we have a need to query VPN client IP from the known FQDN.

**Comment by zachhuff386** [comment]
Users can connect to multiple servers so the VPN subnet is required to match the DNS request to a server. It's possible to change the DNS server to guess a client address which would only be consistent if users connected to only one server at a time. What is the use case for querying users DNS like this?

**Comment by centric-jim** [comment]
Our use case for this is we have Kiosks connecting to our network over the VPN.  We use SolarWinds to monitor the Kiosks.  We want to monitor on the FQDN of the kiosk, for example kiosk-xxx.our.vpn.

This is not a vpn client DNS issue, it is our need to monitor the client via the VPN connection.

**Comment by zachhuff386** [comment]
Added in https://github.com/pritunl/pritunl-dns/commit/ef286e42605ed806a16b2e575900be51dc46d2d8
