### ISSUE TITLE
Server will not start - Cannot resolve host address

### ISSUE THREAD

**Issue by shthead** [pritunl/pritunl#410]
I am running Pritunl 1.24.1025.78-0debian1~jessie enterprise.

After a recent upgrade, one of my servers has stopped working. When the server tries to start I get the following every 10 seconds:
```
[thawing-meadow-3738] Wed Jul 13 08:06:23 2016 OpenVPN 2.3.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Nov 12 2015
[thawing-meadow-3738] Wed Jul 13 08:06:23 2016 library versions: OpenSSL 1.0.1t  3 May 2016, LZO 2.08
[thawing-meadow-3738] Wed Jul 13 08:06:23 2016 Control Channel Authentication: tls-auth using INLINE static key file
[thawing-meadow-3738] Wed Jul 13 08:06:23 2016 RESOLVE: Cannot resolve host address: 103.52.xx.xx: Address family for hostname not supported
[thawing-meadow-3738] Wed Jul 13 08:06:23 2016 Exiting due to fatal error
```
This only occurs for one of my servers - I have other servers that are working fine. The only difference that I can see is that this server has a slightly different network setup.

The server has an RFC1918 IP on eth0. The public IP for the server is bound to loopback as a /32 and the public IP has been routed to the servers RFC1918 IP. My `/etc/network/interfaces` file looks like:
```
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

auto lo:1
iface lo:1 inet static
  address 103.52.xx.xx
  netmask 255.255.255.255

# The primary network interface
allow-hotplug eth0
iface eth0 inet static
  address 192.168.90.17
  netmask 255.255.255.0
  gateway 192.168.90.251
```

In the Pritunl interface, the server is configured with the bind address 103.52.xx.xx. If I remove the bind address traffic is sourced from the wrong IP (192.168.90.17 instead of the public IP) but the server will start so it appears to be related to that.

This appears to have stopped working after it was upgraded to v1.24.0.0.

**Comment by zachhuff386** [comment]
Run `pritunl set vpn.ipv6 false`
