### ISSUE TITLE
Compiling go code for pritunl-dns

### ISSUE THREAD

**Issue by centric-jim** [pritunl/pritunl#419]
Running into issues compiling pritunl-dns.  Could you please provide what the secret sauce is?

~/tmp/go/src/github.com $ set |grep GO
GOPATH=~/tmp/go

 ~/tmp/go/src $ go get github.com/pritunl/pritunl-dns
'# github.com/miekg/dns
github.com/miekg/dns/client.go:443: undefined: tls.DialWithDialer
github.com/miekg/dns/dnssec.go:256: undefined: crypto.Signer
github.com/miekg/dns/dnssec.go:320: undefined: crypto.Signer
github.com/miekg/dns/sig0.go:17: undefined: crypto.Signer

Sorry, I'm very new to compiling go code.  

~/tmp/go/src/github.com $ ls
dropbox  miekg  pritunl  Sirupsen

~/tmp/go/src/github.com $ cd pritunl/

~/tmp/go/src/github.com/pritunl $ go build ./...
'# github.com/miekg/dns
../miekg/dns/client.go:443: undefined: tls.DialWithDialer
../miekg/dns/dnssec.go:256: undefined: crypto.Signer
../miekg/dns/dnssec.go:320: undefined: crypto.Signer
../miekg/dns/sig0.go:17: undefined: crypto.Signer

~/tmp/go/src/github.com/pritunl/pritunl-dns $ go build
'# github.com/miekg/dns
../../miekg/dns/client.go:443: undefined: tls.DialWithDialer
../../miekg/dns/dnssec.go:256: undefined: crypto.Signer
../../miekg/dns/dnssec.go:320: undefined: crypto.Signer
../../miekg/dns/sig0.go:17: undefined: crypto.Signer

~/tmp/go/src/github.com $ go build ./...
Sirupsen/logrus/examples/hook/hook.go:5:2: cannot find package "gopkg.in/gemnasium/logrus-airbrake-hook.v2" in any of:
	/usr/lib/go/src/pkg/gopkg.in/gemnasium/logrus-airbrake-hook.v2 (from $GOROOT)
	~/tmp/go/src/gopkg.in/gemnasium/logrus-airbrake-hook.v2 (from $GOPATH)
dropbox/godropbox/proto/mysql/binlog.pb.go:22:8: cannot find package "github.com/gogo/protobuf/proto" in any of:
	/usr/lib/go/src/pkg/github.com/gogo/protobuf/proto (from $GOROOT)
	~/tmp/go/src/github.com/gogo/protobuf/proto (from $GOPATH)
dropbox/godropbox/gocheck2/checkers.go:13:2: cannot find package "gopkg.in/check.v1" in any of:
	/usr/lib/go/src/pkg/gopkg.in/check.v1 (from $GOROOT)
	~/tmp/go/src/gopkg.in/check.v1 (from $GOPATH)

**Comment by centric-jim** [comment]
It _REALLY_ helps if you're not trying to compile with an OLD version of GO... I was using 1.2.something.  I'm now using 1.4.3.  I see 1.6.x and 1.7.rcX version are out, should I be using one of those?

**Comment by zachhuff386** [comment]
It should be compiled with Go 1.6
