### ISSUE TITLE
PHP API

### ISSUE THREAD

**Issue by VPNSystems** [pritunl/pritunl#426]
I'm trying to set the user id as a variable so I can intergrate with my CMS.

Basically can't pull the user-id from the JSON array (i've tried using rebex). 

Would be helpful if there was some support for this, or an API request to pull a user id with just a username/email. Code posted below.

`<?php

$BASE_URL   = "https://nl.dummysite.net";
$API_TOKEN  = "dummytoken";
$API_SECRET = "dummysecret";

function auth_request($method, $path, $data="") {
    global $BASE_URL, $API_TOKEN, $API_SECRET;

    $auth_timestamp = strval(time());
    $auth_nonce = uniqid();
    $auth_array = array(
        $API_TOKEN,
        $auth_timestamp,
        $auth_nonce,
        strtoupper($method),
        $path,
    );
    if ($data) {
        array_push($auth_array, $data);
    }

    $auth_string = join("&", $auth_array);
    $auth_signature = base64_encode(hash_hmac(
        "sha256", $auth_string, $API_SECRET, true));
    $options = array(
        "http" => array(
            "header"  => array(
                'Content-Type: application/json',
                'Auth-Token: '.$API_TOKEN,
                'Auth-Timestamp: '.$auth_timestamp,
                'Auth-Nonce: '.$auth_nonce,
                'Auth-Signature: '.$auth_signature
            ),
            "method"  => $method,
            "content" => $data,
        ),
    );

    $context = stream_context_create($options);
    return file_get_contents($BASE_URL.$path, false, $context);
};

printf(auth_request("POST", "/user/dummyoriginization",
    json_encode(array(
        "name" => "new_user",
        "email" => "new_user@email.com",
        "disabled" => False
        ))
)."\n"); // Adds user to orginization

//Need to set user-id as a variable $user-id for further intergration

?>`

**Comment by k0nsl** [comment]
@VPNSystems: I hope you're actually not paying  for a subscription... I have never seen someone on GitHub close issues the way @zachhuff386 does it. It's incredible. It's an art form for him, I'm sure.
I could never hire that PR nightmare for my company. Now, don't get me wrong @zachhuff386: your application is good, but I find your attitude lacking (to put it mildly).

**Comment by zachhuff386** [comment]
@k0nsl The user above is violating the terms of the license

https://docs.pritunl.com/docs/white-labeling
https://github.com/pritunl/pritunl/blob/master/LICENSE

**Comment by VPNSystems** [comment]
How am I in vitiation of the license? Thanks.

**Comment by k0nsl** [comment]
@zachhuff386: Well, no, he hasn't violated your ToS (judging solely by the information available to me). Nice excuse, though.
