### ISSUE TITLE
Adding server attached to secondary network interface and ip

### ISSUE THREAD

**Issue by layer3switch** [pritunl/pritunl#60]
Couple of issues/question

 1) creating "server" instance doesn't seems to support single port binding to separate interface/address. Even though the server has two separate interfaces and ip addresses, subsequent server creation setup doesn't allow binding to tcp port "443" after first server binding.

i.e.;

server_1: 1.1.1.1:443
server_2: 1.1.1.2:443

 2) Is there a way to create/add additional "host_id" which can be associated with secondary server instance? I've been trying to create multiple "hosts" via mongodb "hosts" tables with random md5 hash and associate host hash in servers table but this doesn't seems to be working.

**Comment by zachhuff386** [comment]
The enterprise subscription is need for multiple servers. It will display a hosts page and allowing attaching hosts to individual servers.
