### ISSUE TITLE
I can't access to https://my_ip_address:9700/

### ISSUE THREAD

**Issue by FuckTheGFW** [pritunl/pritunl#61]
I install it on Ubuntu 14.10 (Linux 3.16.7-x86_64) on Linode. 

Using these commands:
apt-get install python-software-properties
add-apt-repository -y ppa:pritunl
apt-get update; apt-get install pritunl

What should I do to check problem?

Thanks!

**Comment by zachhuff386** [comment]
Check the output of `cat /var/log/pritunl.log` and `pritunl logs`

**Comment by FuckTheGFW** [comment]
~# cat /var/log/pritunl.log
nothing output

~# pritunl logs
Traceback (most recent call last):
  File "/usr/bin/pritunl", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pymongo>=2.7.1

That's logs. I don't know what they mean.

**Comment by zachhuff386** [comment]
You'll need to install pymongo with pip `pip install pymongo`, python-pymongo is not properly packaged in ubuntu 14.10 it's mssing the egg-info files that are used for checking python requirements http://packages.ubuntu.com/utopic/amd64/python-pymongo/filelist

**Comment by FuckTheGFW** [comment]
Thanks very much! I can access it and set it up now!
