### ISSUE TITLE
VPN not routing for vpn clients

### ISSUE THREAD

**Issue by andrewpe** [pritunl/pritunl#67]
I've been running the server for about 2 or 3 weeks not and it seems like the server can talk to the vpn clients but the clients can't talk to the server (ssh/ping) or other vpn clients (ssh/ping)

Current Config:
1 Server:
   Port: 18260
   Network: 192.68.6.0/24
   DNS Server: 208.67.222.222
   Server Mode: Local Traffic Only
   Local Networks: 192.168.5.0/24
   Adapters: eth0 (public) eth1(rackspace private) eth2(192.168.5.0/24)
   
Error: [snowy-plains-1048][2015-01-29 18:17:30,300][ERROR] 173.186.116.242 - - [29/Jan/2015 18:17:30] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03JJ\x0es\x8e\xa6\xa3\x0cGV^ \x82\xb3Q\xee\x9a&j~\xf7\x1bz\xd8\xbc\xc2M\x8a\x99 +5 \x1f\x93-ek\x02\x83\xdb\xef\xf8~W\xcb\xe5\x87\x0bq\xc2\xca\x93\xbdBd\x8c\xf3\x19\x80\xbe\xcc\x00@\x15\x00*\xc0/\xc0+\x00\x9e\xcc\x14\xcc\x13\xcc\x15\xc0\x14\xc0')

If you need the full log I can give it to you along with any other information.

**Comment by zachhuff386** [comment]
It could be an issue with the firewall or routing check the output of `sudo iptables-save` and `sudo route -n`

**Comment by andrewpe** [comment]
The firewall is good, and the route is in the table.
