### ISSUE TITLE
Error to start pritunl on Centos 7

### ISSUE THREAD

**Issue by cegohub** [pritunl/pritunl#68]
Tryng to start Pritunl. 

Feb 02 20:15:52 srv systemd[1]: Starting Pritunl Daemon...
Feb 02 20:15:52 srv pritunl[437]: Traceback (most recent call last):
Feb 02 20:15:52 srv pritunl[437]: File "/usr/bin/pritunl", line 5, in <module>
Feb 02 20:15:52 srv pritunl[437]: from pkg_resources import load_entry_point
Feb 02 20:15:52 srv pritunl[437]: ImportError: No module named pkg_resources
Feb 02 20:15:52 srv systemd[1]: pritunl.service: control process exited, code=exited status=1
Feb 02 20:15:52 srv systemd[1]: Failed to start Pritunl Daemon.
Feb 02 20:15:52 srv systemd[1]: Unit pritunl.service entered failed state.
Feb 07 15:59:53 srv systemd[1]: Stopped Pritunl Daemon.

**Comment by zachhuff386** [comment]
You first need to install the EPEL then mongodb-server, the commands below will install and start pritunl. The RPM download url on the homepage was also out of date the newest release can be downloaded at https://github.com/pritunl/pritunl/releases

```
wget http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
sudo rpm -Uvh epel-release-7*.rpm
yum install -y pritunl-*.rpm
yum install mongodb-server
systemctl start mongod pritunl
```
