### ISSUE TITLE
Ability To Set Remote To Use DNS

### ISSUE THREAD

**Issue by rholloway** [pritunl/pritunl#72]
It doesn't look like there is a way to set the remote (server) to resolve via DNS rather than static IP through UI. The user .ovpn files always contain the IP address.

It would be useful to have an option to push down a DNS name instead which can help in some enterprise environments.

**Comment by zachhuff386** [comment]
For enterprise edition go to hosts and set the public IP to the dns domain. For standard edition go to settings and set the public IP to the dns domain.
