### ISSUE TITLE
Pritunl client disconnects after some time

### ISSUE THREAD

**Issue by drequivalent** [pritunl/pritunl#74]
The OS on the server is Ubuntu 14.04.1, Pritunl was installed from official PPA.
The OS on the client is Ubuntu 14.10, installtion source is the same.

When connecting to server, the client says "Server connection timed out", although the logs suggest that connection is doing just fine. That is, until the following happens:

Suddenly, the client receives a SIGTERM, and closes connection. From the client perspective it looks like this:

```
Mon Feb 16 22:47:51 2015 us=293134 Closing TUN/TAP interface
Mon Feb 16 22:47:51 2015 us=293226 /sbin/ip addr del dev tun0 192.168.227.2/24
Mon Feb 16 22:48:04 2015 us=161281 SIGTERM[hard,] received, process exiting
```

The server says the following:
```
[restless-refuge-4818] Mon Feb 16 19:48:30 2015 us=688364 54de2297e26f312547f09e38/188.255.60.108:42282 [54de2297e26f312547f09e38] Inactivity timeout (--ping-restart), restarting
[restless-refuge-4818] Mon Feb 16 19:48:30 2015 us=688411 54de2297e26f312547f09e38/188.255.60.108:42282 SIGUSR1[soft,ping-restart] received, client-instance restarting
[restless-refuge-4818] Mon Feb 16 19:48:30 2015 User disconnected org_id=54de2296e26f312547f09e16 user_id=54de2297e26f312547f09e38
```

This is on UDP, but TCP is pretty much the same. Client:

```
Mon Feb 16 22:51:49 2015 us=300080 Initialization Sequence Completed
Mon Feb 16 22:51:49 2015 us=300450 TCP/UDP: Closing socket
Mon Feb 16 22:51:49 2015 us=300587 /sbin/ip route del <REDACTED>/32
Mon Feb 16 22:51:58 2015 us=950798 /sbin/ip route del 0.0.0.0/0
Mon Feb 16 22:52:02 2015 us=166260 /sbin/ip route add 0.0.0.0/0 via 192.168.1.1
Mon Feb 16 22:52:08 2015 us=599322 Closing TUN/TAP interface
Mon Feb 16 22:52:08 2015 us=599400 /sbin/ip addr del dev tun0 192.168.227.2/24
Mon Feb 16 22:52:40 2015 us=765246 SIGTERM[hard,] received, process exiting
```

Server:

```
[restless-refuge-4818] Mon Feb 16 19:51:49 2015 us=656456 54de2297e26f312547f09e38/188.255.60.108:39876 Connection reset, restarting [-1]
[restless-refuge-4818] Mon Feb 16 19:51:49 2015 us=656480 54de2297e26f312547f09e38/188.255.60.108:39876 SIGUSR1[soft,connection-reset] received, client-instance restarting
[restless-refuge-4818] Mon Feb 16 19:51:49 2015 User disconnected org_id=54de2296e26f312547f09e16 user_id=54de2297e26f312547f09e38
[restless-refuge-4818] Mon Feb 16 19:51:49 2015 us=656626 TCP/UDP: Closing socket
```

What is going on here? Do we need ping-restart parameters?

**Comment by zachhuff386** [comment]
The client will send a sigterm if it doesn't detect a working connection, it may be an issue with the client not detecting the valid connection. I will try to reproduce the issue on 14.10.

**Comment by zachhuff386** [comment]
The Pritunl client v1.0.498.25 is working on Ubuntu 14.10 there may be an issue with a firewall or some issue with the server.

**Comment by drequivalent** [comment]
I tried it again, on an absolutely fresh server installation.
It is funny, but - when I use the same config file with just native OpenVPN client-server daemon, it works, and gives me a persistent connection.
May be pritunl client is too quick to kill a connection? Or may be it's because daemon has root privileges?
I'll put last one to the test, and will be back.

**Comment by drequivalent** [comment]
Nope. Still, when I use native OpenVPN, or OpenVPN+NetworkManager, the connection stays where it should.
When I use pritunl client, the connection gets killed. Which is sad, because url-driven setup idea kicks ass.
