### ISSUE TITLE
smtp config appears to require smtp auth

### ISSUE THREAD

**Issue by brentley** [pritunl/pritunl#75]
We already have mail relaying configured and auth handled at the mailer layer. I'd like to just enter "localhost" as my mail server, and have mail processed out the usual way. no auth required. 

Is that possible?

**Comment by zachhuff386** [comment]
The server won't attempt to send mail without a username/password and will only use SSL when sending. I plan on adding more support for different configurations but right now you'll need to use a SSL SMTP server with a username and password.

**Comment by brentley** [comment]
why not make username/password optional? that's all I'm looking for. Let the MTA decide if it should be required, and then error if it is.

**Comment by zachhuff386** [comment]
In a future release there will be more configurations for the SMTP settings including optional username and password.

**Comment by brentley** [comment]
alright. right now, this is a show stopper for us. too bad. :(

--------
Brent
--------
