### ISSUE TITLE
Pritunl writes a wrong IP address in a config file

### ISSUE THREAD

**Issue by drequivalent** [pritunl/pritunl#77]
I have two "servers" on one pritunl instance - TestServ1 (91.212.229.231) and TestServ2 (91.212.229.232).
It seems, pritunl confuses addresses and places 91.212.229.231 into both configuration files.
![screenshot - 26 02 2015 - 20 56 20](https://cloud.githubusercontent.com/assets/1463277/6398264/7999477e-bdfb-11e4-9269-de66d9856ca3.png)

**Comment by zachhuff386** [comment]
To change the remote address go to settings and set the Public IP. On Enterprise go to the hosts tab and  set the Public IP for each host.
