### ISSUE TITLE
Failed to load server status, server error occurred.

### ISSUE THREAD

**Issue by MRACHINI** [pritunl/pritunl#78]
Hello,

I'm getting this error on web interface after successful install:
"Failed to load server status, server error occurred."
also i cant add organization or servers:
"Failed to add organization, server error occurred."

/var/log/pritunl.log:

[undefined][2015-03-08 08:31:11,763][INFO] Generating server ssl cert
[undefined][2015-03-08 08:31:18,812][INFO] Starting setup server
[undefined][2015-03-08 08:31:44,356][INFO] Starting setup server
[undefined][2015-03-08 08:34:41,041][INFO] Starting setup server
[undefined][2015-03-08 08:35:05,227][INFO] Setting db version
  new_ver = '1.0.513.37'
  cur_ver = '1.0.513.37'
[undefined][2015-03-08 08:35:05,276][INFO] Changing administrator password
  username = 'pritunl'
[undefined][2015-03-08 08:35:05,276][INFO] Generating auth token
[undefined][2015-03-08 08:35:05,276][INFO] Generating auth secret

i had openvpn AS installed before and it was working fine, i don't know if this info helps, using Ubuntu 14.

**Comment by zachhuff386** [comment]
Check the output of `pritunl logs`

**Comment by MRACHINI** [comment]
root@:~# pritunl logs
Traceback (most recent call last):
  File "/usr/bin/pritunl", line 9, in <module>
    load_entry_point('pritunl==1.0.513.37', 'console_scripts', 'pritunl')()
  File "/usr/lib/python2.7/dist-packages/pritunl/__main__.py", line 101, in main
    print log_view.get_log_lines(options.limit)
  File "/usr/lib/python2.7/dist-packages/pritunl/logger/view.py", line 88, in get_log_lines
    output += self.format_line(messages[i]) + '\n'
MemoryError

**Comment by zachhuff386** [comment]
Your server is most likely running out of memory, try using more ram at least 512mb and maybe add swap. There may also be an issue with the operating system limits.

**Comment by MRACHINI** [comment]
i think my provider has some problems with their templates, because i have 512MB memory and I'm using a fresh install of Ubuntu 14 minimal, only using ~120mb~!! after installing pritunl

anyway is there some way i can trick it to think there is more memory or maybe increase memory with storage, I'm using a VPS so my options are upgrading to more memory, but i already have more than enough i think. i already tried it and working on a 128MB memory VPS.

**Comment by MRACHINI** [comment]
ok i just installed ubuntu from iso file after i sent it to provider and it runs now, the issue was with the templates provided, now i have another issue

https://github.com/pritunl/pritunl/issues/79
