### ISSUE TITLE
High Ping

### ISSUE THREAD

**Issue by MRACHINI** [pritunl/pritunl#79]
Hello,
I installed both openvpn AS and pritunl several times on several vps and physical machines, and pritunl always has higher ping, for example when i pinged a specific ip from the openvpn AS setup i got 130 average ping, but from same machine with the pritunl setup, i got a range from 130-350 with very unstable ping. i did this back and forth just to make sure my isp is not the problem and also tried it on  3 different vps with same results of always higher ping from pritunl setup.

am i doing something wrong? is there some option that i can disable or enable to get more stable and lower ping? how can i fix this?

**Comment by zachhuff386** [comment]
It's possible the server is having issues encrypting the traffic AS uses lower encryption settings which will work better on a slow server. If the server doesn't have AES-NI try using BF-CBC as the cipher in advanced server settings. Could also be issues with QoS try changing the server port to 1194 udp.

**Comment by MRACHINI** [comment]
care to clarify more please, you mean the ssl settings ?
