### ISSUE TITLE
change user virtual ip address

### ISSUE THREAD

**Issue by cberni** [pritunl/pritunl#81]
Is there a way to change the virtual IP address from user?
Will it be provided in a future version?

I would like to set the IP address from each user...

**Comment by zachhuff386** [comment]
It isn't possible to change the users IP address individually in the admin interface or api. They can be changed on the database but it's possible to corrupt the IP pool if done incorrectly. Setting user IP's will be added to a future version.

**Comment by cberni** [comment]
Is there any estimate of when it will be released?

**Comment by thshdw** [comment]
@zachhuff386 @cberni I'm trying to do something similar. In my openvpn config I tried ```ifconfig-push 192.168.1.22``` but this is not working. Is it possible using an openvpn style directive? Perhaps my syntax is wrong?

**Comment by cberni** [comment]
any update about change the virtual IP address from user? any estimate of when it will be released?
