### ISSUE TITLE
Block outgoing ports

### ISSUE THREAD

**Issue by Bullz3y3** [pritunl/pritunl#85]
Hi,

I'd like to see if I can block certain ports in iptables. When I try with ufw in ubuntu nothing getting effected because already pritunl rules are allowing access.

**Comment by zachhuff386** [comment]
There isn't any options to allow/assist with blocking ports in Pritunl

**Comment by Bullz3y3** [comment]
How can I make regular iptables enabled with pritunl rules exists?
