### ISSUE TITLE
fc21 workstation x64 conflicting packages

### ISSUE THREAD

**Issue by linuxrockstheglobe** [pritunl/pritunl#87]
Hi, after succesfully installing pritunl-1.0.544.74-1.el7.centos.x86_64.rpm via rpm -i packagename.rpm and mongodb with this tutorial http://www.liquidweb.com/kb/how-to-install-mongodb-on-fedora-21/ step 1 a 2 i had no issues but today yum check says it has conflicting issues with python-gridfs python-bsd python-pymongo, how can i resolve this issue, thanks in advance, see u

**Comment by zachhuff386** [comment]
The pritunl centos package includes mongodb and pymongo it will conflict with existing packages.
