### ISSUE TITLE
There is some way to give a static ip to a client ?

### ISSUE THREAD

**Issue by rpluto** [pritunl/pritunl#89]
I have this on my openvpn server the configuration needed on the server 

/etc/openvpn/server.conf
...
ifconfig-pool-persist /var/lib/openvpn/server.ipp
client-config-dir /etc/openvpn/server.ccd
...

cat /var/lib/openvpn/server.ipp
user1,192.168.26.4
user2,192.168.26.8
user3,192.168.26.16

ls /etc/openvpn/server.ccd/
user1
user2
user3

cat /etc/openvpn/server.ccd/user1
ifconfig-push 192.168.26.4 255.255.255.0

cat /etc/openvpn/server.ccd/user2
ifconfig-push 192.168.26.8 255.255.255.0

cat /etc/openvpn/server.ccd/user3
ifconfig-push 192.168.26.16 255.255.255.0

Thx

**Comment by rpluto** [comment]
I put a question mark in the subject, And it is marked as question, but no answer.

maybe it can be a enhancement also.

Thx any way,

**Comment by nikitinsm** [comment]
+1
