### ISSUE TITLE
Ubunutu 14.10 x86 error install

### ISSUE THREAD

**Issue by MichaelAndoid** [pritunl/pritunl#92]
I bought droplet in Ubuntu 14.10 x32 digitalocean and try to install pritunl without sucess.

Ubuntu 14.10 (GNU/Linux 3.16.0-28-generic i686)
Unpacking python-pymongo-ext (2.7.1-1) ...
Processing triggers for ureadahead (0.100.0-16) ...
Setting up python-bson (2.7.1-1) ...
Setting up python-pymongo (2.7.1-1) ...
Setting up pritunl (1.0.544.74-0ubuntu1~utopic) ...
stop: Unknown instance:
pritunl start/running, process 1546
Setting up python-bson-ext (2.7.1-1) ...
Setting up python-gridfs (2.7.1-1) ...
Setting up python-pymongo-ext (2.7.1-1) ...
Processing triggers for ureadahead (0.100.0-16) ...
root@Pritunl-OpenVPN:~#

root@Pritunl-OpenVPN:~#  sudo pritunl start
Traceback (most recent call last):
  File "/usr/bin/pritunl", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pymongo>=2.7.1
root@Pritunl-OpenVPN:~#

Wen i try to open https://myipdroplet:9700/ doesnt work.

**Comment by zachhuff386** [comment]
The ubuntu pymongo package for 14.10 is currently missing the info files needed for python http://packages.ubuntu.com/utopic/amd64/python-pymongo/filelist you will need to install pymongo with pip or use ubuntu 14.04
