### ISSUE TITLE
Authentication is required to start a connection 

### ISSUE THREAD

**Issue by kolorijoo** [pritunl/pritunl#96]
Server asking for user password when I try to connect using printunl client on arch linux. How could i give a password while there is no password form in add user form?
I've tried to use blank password but there is just prompt "Authentication failed! Wrong password?"

**Comment by zachhuff386** [comment]
The client will need the password for getting root privileges needed to create the tun network interface and will also ask for a two-factor authentication code if it has been enabled.

**Comment by kolorijoo** [comment]
That was solved. This is very helpful for me
