### ISSUE TITLE
How to update pritunl?

### ISSUE THREAD

**Issue by MichaelAndoid** [pritunl/pritunl#98]
How to update pritunl in Ubuntu?

Regards

**Comment by zachhuff386** [comment]
Ubuntu and Arch Linux can be updated with the package manager, CentOS can be updated by downloading the new package.

**Comment by MichaelAndoid** [comment]
I dont have gui, what is the command line to update the pritunl?

**Comment by josegonzalez** [comment]
@MichaelAndoid [Here you go](https://askubuntu.com/questions/44122/how-to-upgrade-a-single-package-using-apt-get).

**Comment by MichaelAndoid** [comment]
josegonzalez can you give-me a simple command line for update pritunl in ubuntu?

**Comment by MichaelAndoid** [comment]
No one nows what are the command to update pritunl?

**Comment by MichaelAndoid** [comment]
Ok i findit my self, thanks for all the help :(

To oher ppl with the same doubt
First run:
apt-get update

Then:
apt-get upgrade
